/* ==========================================================================
   NBA My Era — Époques historiques (règles + effectifs légendaires étoffés)
   --------------------------------------------------------------------------
   ⚠️ BEST-EFFORT : rosters de stars curés par époque (~8-10 joueurs/équipe),
   notes indicatives. Certaines franchises portent leur nom d'époque (ERA_TEAM_META).
   Les règles adaptent la simulation (ligne à 3 pts, rythme…). Tableau de playoffs
   unique (8 qualifiés) pour les époques classiques.
   ========================================================================== */

const ERAS = {
  modern: {
    name: 'Époque moderne (2026-27)', year: 2026,
    teams: TEAMS.map(t => t.id),
    rules: { threePA: 1.0, pace: 1.0, fgAdj: 0, confMode: 'conf', note: 'Règles actuelles, tir à 3 pts omniprésent.' },
  },
  e2016: {
    name: 'Années 2010 — Warriors & LeBron (2015-16)', year: 2016,
    teams: ['GSW', 'CLE', 'SAS', 'OKC', 'TOR', 'LAC', 'MIA', 'BOS', 'ATL', 'HOU', 'POR', 'IND', 'DAL', 'MEM', 'WAS', 'NOP'],
    rules: { threePA: 0.82, pace: 0.99, fgAdj: 0, confMode: 'single', note: 'Essor du 3 pts, spacing moderne.' },
  },
  e1996: {
    name: "Années 90 — l'ère Jordan (1995-96)", year: 1996,
    teams: ['CHI', 'OKC', 'ORL', 'HOU', 'SAS', 'UTA', 'LAL', 'NYK', 'IND', 'PHX', 'POR', 'PHI', 'DET', 'MIA', 'ATL', 'DAL'],
    rules: { threePA: 0.5, pace: 0.95, fgAdj: -0.01, confMode: 'single', note: 'Jeu physique, hand-check, 3 pts secondaire.' },
  },
  e1986: {
    name: 'Années 80 — Magic vs Bird (1985-86)', year: 1986,
    teams: ['BOS', 'LAL', 'PHI', 'MIL', 'HOU', 'DET', 'ATL', 'DAL', 'POR', 'DEN', 'UTA', 'PHX', 'CHI', 'NYK', 'WAS', 'BKN'],
    rules: { threePA: 0.14, pace: 1.14, fgAdj: 0, confMode: 'single', note: 'Rythme élevé, ligne à 3 pts rare.' },
  },
  e1968: {
    name: 'Années 60 — Russell & Wilt (1967-68)', year: 1968,
    teams: ['BOS', 'PHI', 'LAL', 'NYK', 'DET', 'ATL', 'GSW', 'SAC', 'CHI', 'OKC'],
    rules: { threePA: 0.0, pace: 1.22, fgAdj: -0.02, confMode: 'single', note: 'Pas de ligne à 3 points, jeu très rapide.' },
  },
};

// Surcharges de nom/ville par époque (franchises relocalisées/renommées)
const ERA_TEAM_META = {
  e2016: {},
  e1996: { OKC: { city: 'Seattle', name: 'SuperSonics' } },
  e1986: { WAS: { city: 'Washington', name: 'Bullets' }, BKN: { city: 'New Jersey', name: 'Nets' } },
  e1968: {
    ATL: { city: 'St. Louis', name: 'Hawks' },
    GSW: { city: 'San Francisco', name: 'Warriors' },
    SAC: { city: 'Cincinnati', name: 'Royals' },
    OKC: { city: 'Seattle', name: 'SuperSonics' },
  },
};

const ERA_ROSTERS = {
  /* ============================== 1967-68 =============================== */
  e1968: {
    BOS: [ { n: 'Bill Russell', pos: 'C', ovr: 94, age: 34 }, { n: 'John Havlicek', pos: 'SF', ovr: 90, age: 28 },
      { n: 'Sam Jones', pos: 'SG', ovr: 88, age: 35 }, { n: 'Bailey Howell', pos: 'PF', ovr: 82, age: 31 },
      { n: 'Larry Siegfried', pos: 'SG', ovr: 78, age: 28 }, { n: 'Satch Sanders', pos: 'SF', ovr: 75, age: 29 },
      { n: 'Don Nelson', pos: 'PF', ovr: 74, age: 27 }, { n: 'Wayne Embry', pos: 'C', ovr: 72, age: 31 },
      { n: 'Bud Olsen', pos: 'PF', ovr: 68, age: 27 } ],
    PHI: [ { n: 'Wilt Chamberlain', pos: 'C', ovr: 97, age: 31 }, { n: 'Hal Greer', pos: 'SG', ovr: 88, age: 31 },
      { n: 'Billy Cunningham', pos: 'SF', ovr: 86, age: 24 }, { n: 'Chet Walker', pos: 'SF', ovr: 82, age: 27 },
      { n: 'Wali Jones', pos: 'PG', ovr: 78, age: 25 }, { n: 'Luke Jackson', pos: 'PF', ovr: 76, age: 26 },
      { n: 'Matt Guokas', pos: 'SG', ovr: 72, age: 23 }, { n: 'Johnny Green', pos: 'PF', ovr: 72, age: 34 } ],
    LAL: [ { n: 'Jerry West', pos: 'SG', ovr: 94, age: 29 }, { n: 'Elgin Baylor', pos: 'SF', ovr: 91, age: 33 },
      { n: 'Gail Goodrich', pos: 'SG', ovr: 80, age: 24 }, { n: 'Archie Clark', pos: 'PG', ovr: 78, age: 26 },
      { n: 'Darrall Imhoff', pos: 'C', ovr: 74, age: 29 }, { n: 'Tommy Hawkins', pos: 'PF', ovr: 72, age: 31 },
      { n: 'Mel Counts', pos: 'C', ovr: 72, age: 26 }, { n: 'Fred Crawford', pos: 'SG', ovr: 70, age: 25 } ],
    NYK: [ { n: 'Willis Reed', pos: 'C', ovr: 88, age: 25 }, { n: 'Walt Frazier', pos: 'PG', ovr: 86, age: 23 },
      { n: 'Dave DeBusschere', pos: 'PF', ovr: 84, age: 27 }, { n: 'Dick Barnett', pos: 'SG', ovr: 80, age: 31 },
      { n: 'Bill Bradley', pos: 'SF', ovr: 78, age: 24 }, { n: 'Cazzie Russell', pos: 'SF', ovr: 76, age: 23 },
      { n: 'Walt Bellamy', pos: 'C', ovr: 80, age: 28 }, { n: 'Dick Van Arsdale', pos: 'SG', ovr: 76, age: 25 } ],
    DET: [ { n: 'Dave Bing', pos: 'PG', ovr: 88, age: 24 }, { n: 'Eddie Miles', pos: 'SG', ovr: 80, age: 27 },
      { n: 'Happy Hairston', pos: 'PF', ovr: 78, age: 25 }, { n: 'Jimmy Walker', pos: 'PG', ovr: 76, age: 23 },
      { n: 'Terry Dischinger', pos: 'PF', ovr: 74, age: 27 }, { n: 'Joe Strawder', pos: 'C', ovr: 72, age: 27 },
      { n: 'Tom Van Arsdale', pos: 'SF', ovr: 76, age: 24 }, { n: 'John Tresvant', pos: 'PF', ovr: 70, age: 28 } ],
    ATL: [ { n: 'Lenny Wilkens', pos: 'PG', ovr: 86, age: 30 }, { n: 'Lou Hudson', pos: 'SF', ovr: 82, age: 23 },
      { n: 'Zelmo Beaty', pos: 'C', ovr: 82, age: 28 }, { n: 'Bill Bridges', pos: 'PF', ovr: 80, age: 28 },
      { n: 'Joe Caldwell', pos: 'SG', ovr: 76, age: 26 }, { n: 'Paul Silas', pos: 'PF', ovr: 76, age: 24 },
      { n: 'Richie Guerin', pos: 'SG', ovr: 74, age: 35 }, { n: 'Jim Davis', pos: 'C', ovr: 68, age: 26 } ],
    GSW: [ { n: 'Rick Barry', pos: 'SF', ovr: 90, age: 23 }, { n: 'Nate Thurmond', pos: 'C', ovr: 88, age: 26 },
      { n: 'Rudy LaRusso', pos: 'PF', ovr: 78, age: 30 }, { n: 'Jeff Mullins', pos: 'SG', ovr: 80, age: 25 },
      { n: 'Al Attles', pos: 'PG', ovr: 76, age: 31 }, { n: 'Fred Hetzel', pos: 'PF', ovr: 74, age: 25 },
      { n: 'Paul Neumann', pos: 'PG', ovr: 72, age: 30 }, { n: 'Clyde Lee', pos: 'C', ovr: 70, age: 23 } ],
    SAC: [ { n: 'Oscar Robertson', pos: 'PG', ovr: 95, age: 29 }, { n: 'Jerry Lucas', pos: 'PF', ovr: 88, age: 27 },
      { n: 'Adrian Smith', pos: 'SG', ovr: 78, age: 31 }, { n: 'Flynn Robinson', pos: 'SG', ovr: 74, age: 26 },
      { n: 'Connie Dierking', pos: 'C', ovr: 74, age: 31 }, { n: 'Bob Love', pos: 'SF', ovr: 74, age: 25 },
      { n: 'Jon McGlocklin', pos: 'SG', ovr: 72, age: 24 } ],
    CHI: [ { n: 'Bob Boozer', pos: 'PF', ovr: 80, age: 30 }, { n: 'Jerry Sloan', pos: 'SG', ovr: 80, age: 25 },
      { n: 'Guy Rodgers', pos: 'PG', ovr: 78, age: 32 }, { n: 'Keith Erickson', pos: 'SF', ovr: 74, age: 24 },
      { n: 'Erwin Mueller', pos: 'C', ovr: 72, age: 24 }, { n: 'McCoy McLemore', pos: 'PF', ovr: 70, age: 25 },
      { n: 'Barry Clemens', pos: 'SF', ovr: 68, age: 24 }, { n: 'Jim Washington', pos: 'PF', ovr: 70, age: 24 } ],
    OKC: [ { n: 'Bob Rule', pos: 'C', ovr: 80, age: 24 }, { n: 'Walt Hazzard', pos: 'PG', ovr: 80, age: 25 },
      { n: 'Tom Meschery', pos: 'PF', ovr: 76, age: 29 }, { n: 'Rod Thorn', pos: 'SG', ovr: 74, age: 26 },
      { n: 'Al Tucker', pos: 'SF', ovr: 72, age: 24 }, { n: 'Bob Weiss', pos: 'PG', ovr: 72, age: 25 },
      { n: 'Tom Kron', pos: 'SG', ovr: 68, age: 25 }, { n: 'Dorie Murrey', pos: 'C', ovr: 68, age: 25 } ],
  },
  /* ============================== 1985-86 =============================== */
  e1986: {
    BOS: [ { n: 'Larry Bird', pos: 'SF', ovr: 96, age: 29 }, { n: 'Kevin McHale', pos: 'PF', ovr: 90, age: 28 },
      { n: 'Robert Parish', pos: 'C', ovr: 86, age: 32 }, { n: 'Dennis Johnson', pos: 'PG', ovr: 82, age: 31 },
      { n: 'Danny Ainge', pos: 'SG', ovr: 80, age: 26 }, { n: 'Bill Walton', pos: 'C', ovr: 78, age: 33 },
      { n: 'Scott Wedman', pos: 'SF', ovr: 74, age: 33 }, { n: 'Jerry Sichting', pos: 'PG', ovr: 72, age: 29 },
      { n: 'David Thirdkill', pos: 'SF', ovr: 66, age: 25 } ],
    LAL: [ { n: 'Magic Johnson', pos: 'PG', ovr: 95, age: 26 }, { n: 'Kareem Abdul-Jabbar', pos: 'C', ovr: 90, age: 38 },
      { n: 'James Worthy', pos: 'SF', ovr: 88, age: 24 }, { n: 'Byron Scott', pos: 'SG', ovr: 82, age: 24 },
      { n: 'Michael Cooper', pos: 'SG', ovr: 80, age: 29 }, { n: 'A.C. Green', pos: 'PF', ovr: 76, age: 22, pot: 84 },
      { n: 'Kurt Rambis', pos: 'PF', ovr: 74, age: 27 }, { n: 'Maurice Lucas', pos: 'PF', ovr: 74, age: 33 },
      { n: 'Mike McGee', pos: 'SG', ovr: 70, age: 26 } ],
    PHI: [ { n: 'Charles Barkley', pos: 'PF', ovr: 88, age: 23, pot: 94 }, { n: 'Julius Erving', pos: 'SF', ovr: 87, age: 35 },
      { n: 'Moses Malone', pos: 'C', ovr: 88, age: 30 }, { n: 'Maurice Cheeks', pos: 'PG', ovr: 84, age: 29 },
      { n: 'Andrew Toney', pos: 'SG', ovr: 80, age: 28 }, { n: 'Bobby Jones', pos: 'SF', ovr: 78, age: 34 },
      { n: 'Sedale Threatt', pos: 'PG', ovr: 72, age: 24 }, { n: 'Clint Richardson', pos: 'SG', ovr: 70, age: 29 } ],
    MIL: [ { n: 'Sidney Moncrief', pos: 'SG', ovr: 87, age: 28 }, { n: 'Terry Cummings', pos: 'PF', ovr: 84, age: 25 },
      { n: 'Paul Pressey', pos: 'SF', ovr: 80, age: 26 }, { n: 'Ricky Pierce', pos: 'SG', ovr: 78, age: 26 },
      { n: 'Alton Lister', pos: 'C', ovr: 74, age: 27 }, { n: 'Craig Hodges', pos: 'SG', ovr: 74, age: 25 },
      { n: 'Paul Mokeski', pos: 'C', ovr: 70, age: 29 }, { n: 'Jerry Reynolds', pos: 'SF', ovr: 70, age: 23 } ],
    HOU: [ { n: 'Hakeem Olajuwon', pos: 'C', ovr: 90, age: 23, pot: 96 }, { n: 'Ralph Sampson', pos: 'C', ovr: 84, age: 25 },
      { n: 'Rodney McCray', pos: 'SF', ovr: 78, age: 24 }, { n: 'Lewis Lloyd', pos: 'SG', ovr: 76, age: 27 },
      { n: 'Robert Reid', pos: 'SF', ovr: 75, age: 30 }, { n: 'Allen Leavell', pos: 'PG', ovr: 74, age: 28 },
      { n: 'Mitchell Wiggins', pos: 'SG', ovr: 72, age: 26 }, { n: 'Jim Petersen', pos: 'PF', ovr: 70, age: 23 } ],
    DET: [ { n: 'Isiah Thomas', pos: 'PG', ovr: 90, age: 24 }, { n: 'Joe Dumars', pos: 'SG', ovr: 80, age: 22, pot: 88 },
      { n: 'Bill Laimbeer', pos: 'C', ovr: 82, age: 28 }, { n: 'Kelly Tripucka', pos: 'SF', ovr: 78, age: 26 },
      { n: 'Vinnie Johnson', pos: 'SG', ovr: 78, age: 29 }, { n: 'Rick Mahorn', pos: 'PF', ovr: 76, age: 27 },
      { n: 'John Long', pos: 'SG', ovr: 72, age: 29 }, { n: 'Sidney Green', pos: 'PF', ovr: 70, age: 24 } ],
    ATL: [ { n: 'Dominique Wilkins', pos: 'SF', ovr: 90, age: 26 }, { n: 'Kevin Willis', pos: 'PF', ovr: 80, age: 23 },
      { n: 'Doc Rivers', pos: 'PG', ovr: 80, age: 24 }, { n: 'Spud Webb', pos: 'PG', ovr: 76, age: 22 },
      { n: 'Randy Wittman', pos: 'SG', ovr: 74, age: 26 }, { n: 'Cliff Levingston', pos: 'PF', ovr: 73, age: 24 },
      { n: 'Tree Rollins', pos: 'C', ovr: 74, age: 30 }, { n: 'Antoine Carr', pos: 'PF', ovr: 72, age: 24 } ],
    DAL: [ { n: 'Mark Aguirre', pos: 'SF', ovr: 84, age: 26 }, { n: 'Rolando Blackman', pos: 'SG', ovr: 84, age: 26 },
      { n: 'Derek Harper', pos: 'PG', ovr: 82, age: 24 }, { n: 'Sam Perkins', pos: 'PF', ovr: 80, age: 24 },
      { n: 'Dale Ellis', pos: 'SG', ovr: 78, age: 25 }, { n: 'Brad Davis', pos: 'PG', ovr: 74, age: 30 },
      { n: 'James Donaldson', pos: 'C', ovr: 76, age: 28 }, { n: 'Detlef Schrempf', pos: 'SF', ovr: 74, age: 23, pot: 84 } ],
    POR: [ { n: 'Clyde Drexler', pos: 'SG', ovr: 87, age: 23, pot: 92 }, { n: 'Kiki Vandeweghe', pos: 'SF', ovr: 82, age: 27 },
      { n: 'Terry Porter', pos: 'PG', ovr: 80, age: 22, pot: 86 }, { n: 'Mychal Thompson', pos: 'C', ovr: 78, age: 31 },
      { n: 'Jerome Kersey', pos: 'SF', ovr: 76, age: 23 }, { n: 'Steve Johnson', pos: 'C', ovr: 74, age: 28 },
      { n: 'Sam Bowie', pos: 'C', ovr: 74, age: 24 }, { n: 'Darnell Valentine', pos: 'PG', ovr: 72, age: 26 } ],
    DEN: [ { n: 'Alex English', pos: 'SF', ovr: 88, age: 32 }, { n: 'Fat Lever', pos: 'PG', ovr: 82, age: 25 },
      { n: 'Dan Issel', pos: 'C', ovr: 80, age: 37 }, { n: 'Calvin Natt', pos: 'PF', ovr: 78, age: 28 },
      { n: 'Bill Hanzlik', pos: 'SG', ovr: 72, age: 28 }, { n: 'Danny Schayes', pos: 'C', ovr: 72, age: 26 },
      { n: 'Wayne Cooper', pos: 'C', ovr: 70, age: 29 }, { n: 'T.R. Dunn', pos: 'SG', ovr: 68, age: 30 } ],
    UTA: [ { n: 'Karl Malone', pos: 'PF', ovr: 86, age: 22, pot: 95 }, { n: 'Adrian Dantley', pos: 'SF', ovr: 86, age: 29 },
      { n: 'John Stockton', pos: 'PG', ovr: 82, age: 23, pot: 92 }, { n: 'Mark Eaton', pos: 'C', ovr: 78, age: 29 },
      { n: 'Thurl Bailey', pos: 'PF', ovr: 78, age: 24 }, { n: 'Rickey Green', pos: 'PG', ovr: 74, age: 31 },
      { n: 'Bobby Hansen', pos: 'SG', ovr: 72, age: 24 }, { n: 'Marc Iavaroni', pos: 'PF', ovr: 68, age: 29 } ],
    PHX: [ { n: 'Larry Nance', pos: 'PF', ovr: 82, age: 26 }, { n: 'Walter Davis', pos: 'SG', ovr: 82, age: 31 },
      { n: 'Alvan Adams', pos: 'C', ovr: 76, age: 31 }, { n: 'James Edwards', pos: 'C', ovr: 76, age: 30 },
      { n: 'Jay Humphries', pos: 'PG', ovr: 74, age: 24 }, { n: 'Mike Sanders', pos: 'SF', ovr: 72, age: 25 },
      { n: 'Rod Foster', pos: 'PG', ovr: 68, age: 25 }, { n: 'Georgi Glouchkov', pos: 'PF', ovr: 66, age: 25 } ],
    CHI: [ { n: 'Michael Jordan', pos: 'SG', ovr: 90, age: 23, pot: 99 }, { n: 'Orlando Woolridge', pos: 'SF', ovr: 80, age: 25 },
      { n: 'Charles Oakley', pos: 'PF', ovr: 78, age: 22, pot: 84 }, { n: 'Dave Corzine', pos: 'C', ovr: 74, age: 30 },
      { n: 'John Paxson', pos: 'PG', ovr: 74, age: 25 }, { n: 'Kyle Macy', pos: 'PG', ovr: 70, age: 28 },
      { n: 'Gene Banks', pos: 'SF', ovr: 72, age: 26 }, { n: 'Mike Smrek', pos: 'C', ovr: 66, age: 24 } ],
    NYK: [ { n: 'Bernard King', pos: 'SF', ovr: 84, age: 29 }, { n: 'Patrick Ewing', pos: 'C', ovr: 82, age: 23, pot: 92 },
      { n: 'Bill Cartwright', pos: 'C', ovr: 76, age: 28 }, { n: 'Gerald Wilkins', pos: 'SG', ovr: 74, age: 22 },
      { n: 'Rory Sparrow', pos: 'PG', ovr: 72, age: 27 }, { n: 'Trent Tucker', pos: 'SG', ovr: 72, age: 26 },
      { n: 'Pat Cummings', pos: 'PF', ovr: 72, age: 29 }, { n: 'Louis Orr', pos: 'SF', ovr: 70, age: 27 } ],
    WAS: [ { n: 'Jeff Malone', pos: 'SG', ovr: 82, age: 24 }, { n: 'Jeff Ruland', pos: 'C', ovr: 78, age: 27 },
      { n: 'Gus Williams', pos: 'PG', ovr: 76, age: 32 }, { n: 'Cliff Robinson', pos: 'PF', ovr: 76, age: 25 },
      { n: 'Dan Roundfield', pos: 'PF', ovr: 74, age: 33 }, { n: 'Manute Bol', pos: 'C', ovr: 70, age: 23 },
      { n: 'Gus Nevárez', pos: 'PG', ovr: 66, age: 24 }, { n: 'Dudley Bradley', pos: 'SG', ovr: 68, age: 29 } ],
    BKN: [ { n: 'Buck Williams', pos: 'PF', ovr: 82, age: 26 }, { n: 'Otis Birdsong', pos: 'SG', ovr: 78, age: 30 },
      { n: 'Micheal Ray Richardson', pos: 'PG', ovr: 78, age: 30 }, { n: 'Mike Gminski', pos: 'C', ovr: 76, age: 26 },
      { n: 'Darryl Dawkins', pos: 'C', ovr: 76, age: 29 }, { n: 'Albert King', pos: 'SF', ovr: 74, age: 26 },
      { n: 'Darwin Cook', pos: 'PG', ovr: 70, age: 27 }, { n: 'Mike O\'Koren', pos: 'SF', ovr: 68, age: 27 } ],
  },
  /* ============================== 1995-96 =============================== */
  e1996: {
    CHI: [ { n: 'Michael Jordan', pos: 'SG', ovr: 99, age: 33 }, { n: 'Scottie Pippen', pos: 'SF', ovr: 92, age: 30 },
      { n: 'Dennis Rodman', pos: 'PF', ovr: 82, age: 34 }, { n: 'Toni Kukoc', pos: 'SF', ovr: 82, age: 27 },
      { n: 'Ron Harper', pos: 'PG', ovr: 78, age: 32 }, { n: 'Steve Kerr', pos: 'SG', ovr: 76, age: 30 },
      { n: 'Luc Longley', pos: 'C', ovr: 74, age: 27 }, { n: 'Bill Wennington', pos: 'C', ovr: 70, age: 32 },
      { n: 'Jud Buechler', pos: 'SF', ovr: 68, age: 27 } ],
    OKC: [ { n: 'Gary Payton', pos: 'PG', ovr: 90, age: 27 }, { n: 'Shawn Kemp', pos: 'PF', ovr: 90, age: 26 },
      { n: 'Detlef Schrempf', pos: 'SF', ovr: 84, age: 33 }, { n: 'Hersey Hawkins', pos: 'SG', ovr: 80, age: 29 },
      { n: 'Sam Perkins', pos: 'PF', ovr: 76, age: 34 }, { n: 'Nate McMillan', pos: 'PG', ovr: 74, age: 31 },
      { n: 'Ervin Johnson', pos: 'C', ovr: 72, age: 28 }, { n: 'Vincent Askew', pos: 'SF', ovr: 70, age: 29 } ],
    ORL: [ { n: 'Shaquille O\'Neal', pos: 'C', ovr: 94, age: 24 }, { n: 'Anfernee Hardaway', pos: 'PG', ovr: 91, age: 24 },
      { n: 'Horace Grant', pos: 'PF', ovr: 80, age: 30 }, { n: 'Nick Anderson', pos: 'SG', ovr: 80, age: 28 },
      { n: 'Dennis Scott', pos: 'SF', ovr: 78, age: 27 }, { n: 'Brian Shaw', pos: 'PG', ovr: 72, age: 30 },
      { n: 'Donald Royal', pos: 'SF', ovr: 68, age: 30 }, { n: 'Jon Koncak', pos: 'C', ovr: 66, age: 32 } ],
    HOU: [ { n: 'Hakeem Olajuwon', pos: 'C', ovr: 92, age: 33 }, { n: 'Clyde Drexler', pos: 'SG', ovr: 86, age: 33 },
      { n: 'Robert Horry', pos: 'PF', ovr: 78, age: 25 }, { n: 'Sam Cassell', pos: 'PG', ovr: 78, age: 26 },
      { n: 'Kenny Smith', pos: 'PG', ovr: 76, age: 30 }, { n: 'Mario Elie', pos: 'SF', ovr: 76, age: 32 },
      { n: 'Chucky Brown', pos: 'PF', ovr: 70, age: 27 }, { n: 'Pete Chilcutt', pos: 'C', ovr: 68, age: 27 } ],
    SAS: [ { n: 'David Robinson', pos: 'C', ovr: 94, age: 30 }, { n: 'Sean Elliott', pos: 'SF', ovr: 82, age: 28 },
      { n: 'Avery Johnson', pos: 'PG', ovr: 80, age: 31 }, { n: 'Vinny Del Negro', pos: 'SG', ovr: 76, age: 29 },
      { n: 'Chuck Person', pos: 'SF', ovr: 76, age: 31 }, { n: 'Will Perdue', pos: 'C', ovr: 72, age: 30 },
      { n: 'Doc Rivers', pos: 'PG', ovr: 72, age: 34 }, { n: 'J.R. Reid', pos: 'PF', ovr: 70, age: 28 } ],
    UTA: [ { n: 'Karl Malone', pos: 'PF', ovr: 92, age: 32 }, { n: 'John Stockton', pos: 'PG', ovr: 88, age: 33 },
      { n: 'Jeff Hornacek', pos: 'SG', ovr: 82, age: 32 }, { n: 'Bryon Russell', pos: 'SF', ovr: 74, age: 25 },
      { n: 'Antoine Carr', pos: 'PF', ovr: 74, age: 34 }, { n: 'Greg Ostertag', pos: 'C', ovr: 72, age: 23 },
      { n: 'Chris Morris', pos: 'SF', ovr: 72, age: 29 }, { n: 'Howard Eisley', pos: 'PG', ovr: 68, age: 23 } ],
    LAL: [ { n: 'Eddie Jones', pos: 'SG', ovr: 82, age: 24 }, { n: 'Magic Johnson', pos: 'PG', ovr: 82, age: 36 },
      { n: 'Vlade Divac', pos: 'C', ovr: 82, age: 28 }, { n: 'Nick Van Exel', pos: 'PG', ovr: 80, age: 24 },
      { n: 'Cedric Ceballos', pos: 'SF', ovr: 80, age: 26 }, { n: 'Elden Campbell', pos: 'PF', ovr: 76, age: 27 },
      { n: 'Anthony Peeler', pos: 'SG', ovr: 72, age: 26 }, { n: 'Corie Blount', pos: 'PF', ovr: 68, age: 26 } ],
    NYK: [ { n: 'Patrick Ewing', pos: 'C', ovr: 90, age: 33 }, { n: 'John Starks', pos: 'SG', ovr: 82, age: 30 },
      { n: 'Anthony Mason', pos: 'PF', ovr: 80, age: 29 }, { n: 'Charles Oakley', pos: 'PF', ovr: 80, age: 32 },
      { n: 'Derek Harper', pos: 'PG', ovr: 78, age: 34 }, { n: 'Allan Houston', pos: 'SG', ovr: 78, age: 25 },
      { n: 'Charlie Ward', pos: 'PG', ovr: 70, age: 25 }, { n: 'Hubert Davis', pos: 'SG', ovr: 72, age: 25 } ],
    IND: [ { n: 'Reggie Miller', pos: 'SG', ovr: 88, age: 30 }, { n: 'Rik Smits', pos: 'C', ovr: 82, age: 29 },
      { n: 'Mark Jackson', pos: 'PG', ovr: 80, age: 31 }, { n: 'Dale Davis', pos: 'PF', ovr: 80, age: 27 },
      { n: 'Antonio Davis', pos: 'PF', ovr: 78, age: 27 }, { n: 'Derrick McKey', pos: 'SF', ovr: 76, age: 29 },
      { n: 'Ricky Pierce', pos: 'SG', ovr: 72, age: 36 }, { n: 'Travis Best', pos: 'PG', ovr: 70, age: 23 } ],
    PHX: [ { n: 'Charles Barkley', pos: 'PF', ovr: 90, age: 33 }, { n: 'Kevin Johnson', pos: 'PG', ovr: 86, age: 30 },
      { n: 'Michael Finley', pos: 'SG', ovr: 80, age: 23, pot: 88 }, { n: 'A.C. Green', pos: 'PF', ovr: 76, age: 32 },
      { n: 'Wesley Person', pos: 'SG', ovr: 76, age: 24 }, { n: 'Danny Manning', pos: 'PF', ovr: 78, age: 29 },
      { n: 'Wayman Tisdale', pos: 'PF', ovr: 74, age: 32 }, { n: 'Elliot Perry', pos: 'PG', ovr: 70, age: 27 } ],
    POR: [ { n: 'Arvydas Sabonis', pos: 'C', ovr: 84, age: 31 }, { n: 'Rod Strickland', pos: 'PG', ovr: 82, age: 29 },
      { n: 'Clifford Robinson', pos: 'SF', ovr: 80, age: 29 }, { n: 'Isaiah Rider', pos: 'SG', ovr: 78, age: 24 },
      { n: 'Buck Williams', pos: 'PF', ovr: 76, age: 35 }, { n: 'Aaron McKie', pos: 'SG', ovr: 74, age: 23 },
      { n: 'Gary Trent', pos: 'PF', ovr: 70, age: 21 }, { n: 'James Robinson', pos: 'PG', ovr: 68, age: 25 } ],
    PHI: [ { n: 'Jerry Stackhouse', pos: 'SG', ovr: 82, age: 21, pot: 88 }, { n: 'Derrick Coleman', pos: 'PF', ovr: 80, age: 28 },
      { n: 'Clarence Weatherspoon', pos: 'PF', ovr: 78, age: 25 }, { n: 'Vernon Maxwell', pos: 'SG', ovr: 74, age: 30 },
      { n: 'Sharone Wright', pos: 'C', ovr: 72, age: 22, pot: 80 }, { n: 'Rex Walters', pos: 'PG', ovr: 70, age: 25 },
      { n: 'Trevor Ruffin', pos: 'PG', ovr: 68, age: 24 }, { n: 'Scott Williams', pos: 'C', ovr: 68, age: 28 } ],
    DET: [ { n: 'Grant Hill', pos: 'SF', ovr: 88, age: 23, pot: 92 }, { n: 'Joe Dumars', pos: 'SG', ovr: 82, age: 32 },
      { n: 'Otis Thorpe', pos: 'PF', ovr: 78, age: 33 },
      { n: 'Lindsey Hunter', pos: 'PG', ovr: 74, age: 25 }, { n: 'Terry Mills', pos: 'PF', ovr: 74, age: 28 },
      { n: 'Theo Ratliff', pos: 'C', ovr: 72, age: 22, pot: 82 }, { n: 'Michael Curry', pos: 'SG', ovr: 68, age: 27 } ],
    MIA: [ { n: 'Alonzo Mourning', pos: 'C', ovr: 88, age: 26 }, { n: 'Tim Hardaway', pos: 'PG', ovr: 84, age: 29 },
      { n: 'Rex Chapman', pos: 'SG', ovr: 76, age: 28 }, { n: 'P.J. Brown', pos: 'PF', ovr: 76, age: 26 },
      { n: 'Kurt Thomas', pos: 'PF', ovr: 72, age: 23 }, { n: 'Voshon Lenard', pos: 'SG', ovr: 72, age: 23 },
      { n: 'Keith Askins', pos: 'SF', ovr: 68, age: 28 }, { n: 'Bimbo Coles', pos: 'PG', ovr: 70, age: 27 } ],
    ATL: [ { n: 'Mookie Blaylock', pos: 'PG', ovr: 82, age: 29 }, { n: 'Steve Smith', pos: 'SG', ovr: 82, age: 27 },
      { n: 'Christian Laettner', pos: 'PF', ovr: 80, age: 26 }, { n: 'Ken Norman', pos: 'SF', ovr: 74, age: 32 },
      { n: 'Grant Long', pos: 'PF', ovr: 74, age: 29 }, { n: 'Tyrone Corbin', pos: 'SF', ovr: 72, age: 33 },
      { n: 'Craig Ehlo', pos: 'SG', ovr: 70, age: 35 }, { n: 'Alan Henderson', pos: 'PF', ovr: 68, age: 23 } ],
    DAL: [ { n: 'Jason Kidd', pos: 'PG', ovr: 84, age: 23, pot: 90 }, { n: 'Jim Jackson', pos: 'SG', ovr: 80, age: 25 },
      { n: 'Jamal Mashburn', pos: 'SF', ovr: 80, age: 23 }, { n: 'Popeye Jones', pos: 'PF', ovr: 74, age: 25 },
      { n: 'George McCloud', pos: 'SF', ovr: 74, age: 28 }, { n: 'Cherokee Parks', pos: 'C', ovr: 70, age: 23 },
      { n: 'Tony Dumas', pos: 'SG', ovr: 68, age: 23 }, { n: 'Loren Meyer', pos: 'C', ovr: 66, age: 23 } ],
  },
  /* ============================== 2015-16 =============================== */
  e2016: {
    GSW: [ { n: 'Stephen Curry', pos: 'PG', ovr: 96, age: 28 }, { n: 'Klay Thompson', pos: 'SG', ovr: 88, age: 26 },
      { n: 'Draymond Green', pos: 'PF', ovr: 86, age: 26 }, { n: 'Andre Iguodala', pos: 'SF', ovr: 80, age: 32 },
      { n: 'Andrew Bogut', pos: 'C', ovr: 78, age: 31 }, { n: 'Harrison Barnes', pos: 'SF', ovr: 78, age: 24 },
      { n: 'Shaun Livingston', pos: 'PG', ovr: 76, age: 30 }, { n: 'Festus Ezeli', pos: 'C', ovr: 72, age: 26 },
      { n: 'Leandro Barbosa', pos: 'SG', ovr: 72, age: 33 } ],
    CLE: [ { n: 'LeBron James', pos: 'SF', ovr: 96, age: 31 }, { n: 'Kyrie Irving', pos: 'PG', ovr: 88, age: 24 },
      { n: 'Kevin Love', pos: 'PF', ovr: 84, age: 27 }, { n: 'Tristan Thompson', pos: 'C', ovr: 78, age: 25 },
      { n: 'J.R. Smith', pos: 'SG', ovr: 78, age: 30 }, { n: 'Channing Frye', pos: 'C', ovr: 74, age: 33 },
      { n: 'Iman Shumpert', pos: 'SG', ovr: 74, age: 26 }, { n: 'Matthew Dellavedova', pos: 'PG', ovr: 72, age: 25 },
      { n: 'Richard Jefferson', pos: 'SF', ovr: 72, age: 35 } ],
    SAS: [ { n: 'Kawhi Leonard', pos: 'SF', ovr: 90, age: 24, pot: 95 }, { n: 'LaMarcus Aldridge', pos: 'PF', ovr: 86, age: 31 },
      { n: 'Tim Duncan', pos: 'C', ovr: 82, age: 40 }, { n: 'Tony Parker', pos: 'PG', ovr: 82, age: 34 },
      { n: 'Manu Ginobili', pos: 'SG', ovr: 80, age: 39 }, { n: 'Danny Green', pos: 'SG', ovr: 78, age: 29 },
      { n: 'Patty Mills', pos: 'PG', ovr: 74, age: 28 }, { n: 'David West', pos: 'PF', ovr: 76, age: 35 },
      { n: 'Boris Diaw', pos: 'PF', ovr: 74, age: 34 } ],
    OKC: [ { n: 'Kevin Durant', pos: 'SF', ovr: 95, age: 28 }, { n: 'Russell Westbrook', pos: 'PG', ovr: 92, age: 28 },
      { n: 'Serge Ibaka', pos: 'PF', ovr: 82, age: 27 }, { n: 'Steven Adams', pos: 'C', ovr: 80, age: 23, pot: 86 },
      { n: 'Enes Kanter', pos: 'C', ovr: 78, age: 24 }, { n: 'Andre Roberson', pos: 'SF', ovr: 74, age: 25 },
      { n: 'Dion Waiters', pos: 'SG', ovr: 76, age: 25 }, { n: 'Cameron Payne', pos: 'PG', ovr: 70, age: 22 } ],
    TOR: [ { n: 'Kyle Lowry', pos: 'PG', ovr: 86, age: 30 }, { n: 'DeMar DeRozan', pos: 'SG', ovr: 85, age: 27 },
      { n: 'Jonas Valanciunas', pos: 'C', ovr: 80, age: 24 }, { n: 'DeMarre Carroll', pos: 'SF', ovr: 76, age: 30 },
      { n: 'Cory Joseph', pos: 'PG', ovr: 74, age: 25 }, { n: 'Patrick Patterson', pos: 'PF', ovr: 74, age: 27 },
      { n: 'Terrence Ross', pos: 'SG', ovr: 74, age: 25 }, { n: 'Bismack Biyombo', pos: 'C', ovr: 76, age: 24 } ],
    LAC: [ { n: 'Chris Paul', pos: 'PG', ovr: 90, age: 31 }, { n: 'Blake Griffin', pos: 'PF', ovr: 88, age: 27 },
      { n: 'DeAndre Jordan', pos: 'C', ovr: 84, age: 28 }, { n: 'J.J. Redick', pos: 'SG', ovr: 80, age: 32 },
      { n: 'Jamal Crawford', pos: 'SG', ovr: 78, age: 36 }, { n: 'Luc Mbah a Moute', pos: 'SF', ovr: 72, age: 30 },
      { n: 'Paul Pierce', pos: 'SF', ovr: 74, age: 39 }, { n: 'Austin Rivers', pos: 'PG', ovr: 72, age: 24 } ],
    MIA: [ { n: 'Dwyane Wade', pos: 'SG', ovr: 86, age: 34 }, { n: 'Chris Bosh', pos: 'PF', ovr: 84, age: 32 },
      { n: 'Hassan Whiteside', pos: 'C', ovr: 82, age: 27 }, { n: 'Goran Dragic', pos: 'PG', ovr: 82, age: 30 },
      { n: 'Luol Deng', pos: 'SF', ovr: 78, age: 31 }, { n: 'Justise Winslow', pos: 'SF', ovr: 74, age: 20, pot: 84 },
      { n: 'Josh Richardson', pos: 'SG', ovr: 72, age: 23 }, { n: 'Gerald Green', pos: 'SG', ovr: 72, age: 30 } ],
    BOS: [ { n: 'Isaiah Thomas', pos: 'PG', ovr: 86, age: 27 }, { n: 'Avery Bradley', pos: 'SG', ovr: 80, age: 26 },
      { n: 'Jae Crowder', pos: 'SF', ovr: 78, age: 26 }, { n: 'Marcus Smart', pos: 'PG', ovr: 78, age: 22, pot: 84 },
      { n: 'Kelly Olynyk', pos: 'C', ovr: 76, age: 25 }, { n: 'Amir Johnson', pos: 'PF', ovr: 74, age: 29 },
      { n: 'Jared Sullinger', pos: 'PF', ovr: 74, age: 24 }, { n: 'Evan Turner', pos: 'SG', ovr: 74, age: 28 } ],
    ATL: [ { n: 'Paul Millsap', pos: 'PF', ovr: 85, age: 31 }, { n: 'Al Horford', pos: 'C', ovr: 84, age: 30 },
      { n: 'Jeff Teague', pos: 'PG', ovr: 80, age: 28 }, { n: 'Kyle Korver', pos: 'SG', ovr: 80, age: 35 },
      { n: 'Dennis Schroder', pos: 'PG', ovr: 78, age: 23, pot: 85 }, { n: 'Kent Bazemore', pos: 'SF', ovr: 76, age: 27 },
      { n: 'Thabo Sefolosha', pos: 'SF', ovr: 72, age: 32 }, { n: 'Tiago Splitter', pos: 'C', ovr: 74, age: 31 } ],
    HOU: [ { n: 'James Harden', pos: 'SG', ovr: 90, age: 27 }, { n: 'Dwight Howard', pos: 'C', ovr: 82, age: 30 },
      { n: 'Trevor Ariza', pos: 'SF', ovr: 78, age: 31 }, { n: 'Patrick Beverley', pos: 'PG', ovr: 76, age: 28 },
      { n: 'Michael Beasley', pos: 'SF', ovr: 74, age: 27 }, { n: 'Corey Brewer', pos: 'SF', ovr: 72, age: 30 },
      { n: 'Terrence Jones', pos: 'PF', ovr: 74, age: 24 }, { n: 'K.J. McDaniels', pos: 'SG', ovr: 70, age: 23 } ],
    POR: [ { n: 'Damian Lillard', pos: 'PG', ovr: 88, age: 26 }, { n: 'C.J. McCollum', pos: 'SG', ovr: 84, age: 25 },
      { n: 'Al-Farouq Aminu', pos: 'SF', ovr: 78, age: 26 }, { n: 'Mason Plumlee', pos: 'C', ovr: 78, age: 26 },
      { n: 'Maurice Harkless', pos: 'SF', ovr: 74, age: 23 }, { n: 'Ed Davis', pos: 'PF', ovr: 74, age: 27 },
      { n: 'Allen Crabbe', pos: 'SG', ovr: 74, age: 24 }, { n: 'Meyers Leonard', pos: 'C', ovr: 72, age: 24 } ],
    IND: [ { n: 'Paul George', pos: 'SF', ovr: 88, age: 26 }, { n: 'Monta Ellis', pos: 'SG', ovr: 80, age: 30 },
      { n: 'George Hill', pos: 'PG', ovr: 80, age: 30 }, { n: 'Myles Turner', pos: 'C', ovr: 80, age: 20, pot: 89 },
      { n: 'C.J. Miles', pos: 'SF', ovr: 74, age: 29 }, { n: 'Ian Mahinmi', pos: 'C', ovr: 74, age: 29 },
      { n: 'Jordan Hill', pos: 'PF', ovr: 72, age: 28 }, { n: 'Rodney Stuckey', pos: 'SG', ovr: 72, age: 30 } ],
    DAL: [ { n: 'Dirk Nowitzki', pos: 'PF', ovr: 84, age: 37 }, { n: 'Wesley Matthews', pos: 'SG', ovr: 78, age: 29 },
      { n: 'Chandler Parsons', pos: 'SF', ovr: 78, age: 27 }, { n: 'Deron Williams', pos: 'PG', ovr: 78, age: 31 },
      { n: 'Zaza Pachulia', pos: 'C', ovr: 76, age: 32 }, { n: 'J.J. Barea', pos: 'PG', ovr: 74, age: 31 },
      { n: 'Raymond Felton', pos: 'PG', ovr: 72, age: 31 }, { n: 'Dwight Powell', pos: 'PF', ovr: 70, age: 24 } ],
    MEM: [ { n: 'Marc Gasol', pos: 'C', ovr: 84, age: 31 }, { n: 'Mike Conley', pos: 'PG', ovr: 84, age: 28 },
      { n: 'Zach Randolph', pos: 'PF', ovr: 80, age: 34 }, { n: 'Tony Allen', pos: 'SG', ovr: 76, age: 34 },
      { n: 'Courtney Lee', pos: 'SG', ovr: 74, age: 30 }, { n: 'Matt Barnes', pos: 'SF', ovr: 74, age: 36 },
      { n: 'JaMychal Green', pos: 'PF', ovr: 72, age: 25 }, { n: 'Vince Carter', pos: 'SG', ovr: 74, age: 39 } ],
    WAS: [ { n: 'John Wall', pos: 'PG', ovr: 86, age: 25 }, { n: 'Bradley Beal', pos: 'SG', ovr: 82, age: 22, pot: 90 },
      { n: 'Otto Porter Jr.', pos: 'SF', ovr: 76, age: 23 }, { n: 'Marcin Gortat', pos: 'C', ovr: 78, age: 32 },
      { n: 'Nene', pos: 'C', ovr: 74, age: 33 }, { n: 'Markieff Morris', pos: 'PF', ovr: 74, age: 26 },
      { n: 'Ramon Sessions', pos: 'PG', ovr: 72, age: 30 }, { n: 'Jared Dudley', pos: 'SF', ovr: 72, age: 30 } ],
    NOP: [ { n: 'Anthony Davis', pos: 'C', ovr: 88, age: 23, pot: 95 }, { n: 'Jrue Holiday', pos: 'PG', ovr: 82, age: 25 },
      { n: 'Tyreke Evans', pos: 'SG', ovr: 78, age: 26 }, { n: 'Ryan Anderson', pos: 'PF', ovr: 76, age: 28 },
      { n: 'Eric Gordon', pos: 'SG', ovr: 76, age: 27 }, { n: 'Omer Asik', pos: 'C', ovr: 72, age: 30 },
      { n: 'Norris Cole', pos: 'PG', ovr: 70, age: 27 }, { n: 'Dante Cunningham', pos: 'PF', ovr: 70, age: 29 } ],
  },
};
