/* ==========================================================================
   NBA My Era — Effectifs réels (instantané ~2024-25)
   --------------------------------------------------------------------------
   n = nom, pos = poste, ovr = note, age = âge (approx.), pot = potentiel (opt.)
   Instantané indicatif et éditable en jeu (transferts, coupes, agents libres).
   Le fond de banc est complété automatiquement par des joueurs générés.
   ========================================================================== */

const REAL_ROSTERS = {
  /* ------------------------------- EST ---------------------------------- */
  BOS: [
    { n: 'Jayson Tatum', pos: 'SF', ovr: 96, age: 27 },
    { n: 'Jaylen Brown', pos: 'SG', ovr: 91, age: 28 },
    { n: 'Kristaps Porzingis', pos: 'C', ovr: 87, age: 29 },
    { n: 'Jrue Holiday', pos: 'PG', ovr: 85, age: 34 },
    { n: 'Derrick White', pos: 'SG', ovr: 85, age: 30 },
    { n: 'Al Horford', pos: 'C', ovr: 81, age: 38 },
    { n: 'Payton Pritchard', pos: 'PG', ovr: 80, age: 27 },
    { n: 'Sam Hauser', pos: 'SF', ovr: 76, age: 27 },
    { n: 'Luke Kornet', pos: 'C', ovr: 74, age: 29 },
  ],
  BKN: [
    { n: 'Cam Thomas', pos: 'SG', ovr: 82, age: 23 },
    { n: 'Cameron Johnson', pos: 'SF', ovr: 80, age: 28 },
    { n: 'Nic Claxton', pos: 'C', ovr: 81, age: 25 },
    { n: 'Dennis Schroder', pos: 'PG', ovr: 78, age: 31 },
    { n: 'Dorian Finney-Smith', pos: 'SF', ovr: 77, age: 31 },
    { n: "Day'Ron Sharpe", pos: 'C', ovr: 74, age: 23 },
    { n: 'Noah Clowney', pos: 'PF', ovr: 73, age: 20, pot: 82 },
    { n: 'Keon Johnson', pos: 'SG', ovr: 73, age: 22 },
  ],
  NYK: [
    { n: 'Jalen Brunson', pos: 'PG', ovr: 91, age: 28 },
    { n: 'Karl-Anthony Towns', pos: 'C', ovr: 88, age: 29 },
    { n: 'Mikal Bridges', pos: 'SF', ovr: 85, age: 28 },
    { n: 'OG Anunoby', pos: 'SF', ovr: 84, age: 27 },
    { n: 'Josh Hart', pos: 'SG', ovr: 82, age: 29 },
    { n: 'Mitchell Robinson', pos: 'C', ovr: 79, age: 26 },
    { n: 'Miles McBride', pos: 'PG', ovr: 76, age: 24 },
    { n: 'Cameron Payne', pos: 'PG', ovr: 73, age: 30 },
  ],
  PHI: [
    { n: 'Joel Embiid', pos: 'C', ovr: 95, age: 31 },
    { n: 'Tyrese Maxey', pos: 'PG', ovr: 89, age: 24 },
    { n: 'Paul George', pos: 'SF', ovr: 87, age: 34 },
    { n: 'Kelly Oubre Jr.', pos: 'SG', ovr: 79, age: 29 },
    { n: 'Caleb Martin', pos: 'SF', ovr: 77, age: 29 },
    { n: 'Andre Drummond', pos: 'C', ovr: 76, age: 31 },
    { n: 'Eric Gordon', pos: 'SG', ovr: 74, age: 36 },
    { n: 'Jared McCain', pos: 'PG', ovr: 75, age: 21, pot: 85 },
  ],
  TOR: [
    { n: 'Scottie Barnes', pos: 'PF', ovr: 86, age: 23, pot: 92 },
    { n: 'RJ Barrett', pos: 'SG', ovr: 82, age: 24 },
    { n: 'Immanuel Quickley', pos: 'PG', ovr: 81, age: 25 },
    { n: 'Jakob Poeltl', pos: 'C', ovr: 80, age: 29 },
    { n: 'Gradey Dick', pos: 'SG', ovr: 76, age: 21, pot: 84 },
    { n: 'Ochai Agbaji', pos: 'SG', ovr: 74, age: 24 },
    { n: 'Chris Boucher', pos: 'PF', ovr: 75, age: 32 },
    { n: 'Jamal Shead', pos: 'PG', ovr: 72, age: 22 },
  ],
  CHI: [
    { n: 'Zach LaVine', pos: 'SG', ovr: 83, age: 30 },
    { n: 'Coby White', pos: 'PG', ovr: 81, age: 25 },
    { n: 'Nikola Vucevic', pos: 'C', ovr: 81, age: 34 },
    { n: 'Josh Giddey', pos: 'PG', ovr: 80, age: 22 },
    { n: 'Ayo Dosunmu', pos: 'SG', ovr: 77, age: 25 },
    { n: 'Patrick Williams', pos: 'PF', ovr: 76, age: 23 },
    { n: 'Lonzo Ball', pos: 'PG', ovr: 74, age: 27 },
    { n: 'Jalen Smith', pos: 'PF', ovr: 74, age: 25 },
  ],
  CLE: [
    { n: 'Donovan Mitchell', pos: 'SG', ovr: 92, age: 28 },
    { n: 'Evan Mobley', pos: 'PF', ovr: 88, age: 23, pot: 93 },
    { n: 'Darius Garland', pos: 'PG', ovr: 86, age: 25 },
    { n: 'Jarrett Allen', pos: 'C', ovr: 84, age: 26 },
    { n: 'Max Strus', pos: 'SF', ovr: 79, age: 29 },
    { n: 'Caris LeVert', pos: 'SG', ovr: 78, age: 30 },
    { n: 'Ty Jerome', pos: 'PG', ovr: 77, age: 27 },
    { n: 'Isaac Okoro', pos: 'SF', ovr: 75, age: 24 },
  ],
  DET: [
    { n: 'Cade Cunningham', pos: 'PG', ovr: 87, age: 23, pot: 93 },
    { n: 'Jaden Ivey', pos: 'SG', ovr: 79, age: 23 },
    { n: 'Jalen Duren', pos: 'C', ovr: 80, age: 21, pot: 86 },
    { n: 'Tobias Harris', pos: 'SF', ovr: 79, age: 32 },
    { n: 'Ausar Thompson', pos: 'SF', ovr: 78, age: 22, pot: 87 },
    { n: 'Isaiah Stewart', pos: 'C', ovr: 77, age: 23 },
    { n: 'Tim Hardaway Jr.', pos: 'SG', ovr: 77, age: 32 },
    { n: 'Marcus Sasser', pos: 'PG', ovr: 74, age: 24 },
  ],
  IND: [
    { n: 'Tyrese Haliburton', pos: 'PG', ovr: 90, age: 24 },
    { n: 'Pascal Siakam', pos: 'PF', ovr: 87, age: 30 },
    { n: 'Myles Turner', pos: 'C', ovr: 83, age: 28 },
    { n: 'Bennedict Mathurin', pos: 'SG', ovr: 80, age: 22, pot: 87 },
    { n: 'Aaron Nesmith', pos: 'SF', ovr: 78, age: 25 },
    { n: 'Andrew Nembhard', pos: 'PG', ovr: 78, age: 25 },
    { n: 'Obi Toppin', pos: 'PF', ovr: 77, age: 26 },
    { n: 'T.J. McConnell', pos: 'PG', ovr: 76, age: 32 },
  ],
  MIL: [
    { n: 'Giannis Antetokounmpo', pos: 'PF', ovr: 96, age: 30 },
    { n: 'Damian Lillard', pos: 'PG', ovr: 88, age: 34 },
    { n: 'Khris Middleton', pos: 'SF', ovr: 83, age: 33 },
    { n: 'Brook Lopez', pos: 'C', ovr: 81, age: 36 },
    { n: 'Bobby Portis', pos: 'PF', ovr: 80, age: 29 },
    { n: 'Gary Trent Jr.', pos: 'SG', ovr: 77, age: 26 },
    { n: 'Pat Connaughton', pos: 'SG', ovr: 73, age: 32 },
    { n: 'AJ Green', pos: 'SG', ovr: 73, age: 25 },
  ],
  ATL: [
    { n: 'Trae Young', pos: 'PG', ovr: 88, age: 26 },
    { n: 'Jalen Johnson', pos: 'PF', ovr: 83, age: 23, pot: 89 },
    { n: 'Dyson Daniels', pos: 'SG', ovr: 80, age: 22, pot: 86 },
    { n: 'Clint Capela', pos: 'C', ovr: 79, age: 30 },
    { n: 'Onyeka Okongwu', pos: 'C', ovr: 79, age: 24 },
    { n: 'Bogdan Bogdanovic', pos: 'SG', ovr: 80, age: 32 },
    { n: 'Zaccharie Risacher', pos: 'SF', ovr: 76, age: 20, pot: 87 },
    { n: "De'Andre Hunter", pos: 'SF', ovr: 79, age: 27 },
  ],
  CHA: [
    { n: 'LaMelo Ball', pos: 'PG', ovr: 86, age: 23, pot: 91 },
    { n: 'Brandon Miller', pos: 'SF', ovr: 82, age: 22, pot: 89 },
    { n: 'Miles Bridges', pos: 'SF', ovr: 80, age: 27 },
    { n: 'Mark Williams', pos: 'C', ovr: 78, age: 23, pot: 85 },
    { n: 'Grant Williams', pos: 'PF', ovr: 76, age: 26 },
    { n: 'Nick Richards', pos: 'C', ovr: 75, age: 27 },
    { n: 'Josh Green', pos: 'SG', ovr: 75, age: 24 },
    { n: 'Tidjane Salaun', pos: 'PF', ovr: 72, age: 19, pot: 83 },
  ],
  MIA: [
    { n: 'Jimmy Butler', pos: 'SF', ovr: 89, age: 35 },
    { n: 'Bam Adebayo', pos: 'C', ovr: 88, age: 27 },
    { n: 'Tyler Herro', pos: 'SG', ovr: 84, age: 25 },
    { n: 'Terry Rozier', pos: 'PG', ovr: 80, age: 30 },
    { n: 'Jaime Jaquez Jr.', pos: 'SG', ovr: 78, age: 24 },
    { n: 'Duncan Robinson', pos: 'SF', ovr: 78, age: 30 },
    { n: 'Nikola Jovic', pos: 'PF', ovr: 76, age: 21, pot: 84 },
    { n: 'Kevin Love', pos: 'PF', ovr: 75, age: 36 },
  ],
  ORL: [
    { n: 'Paolo Banchero', pos: 'PF', ovr: 88, age: 22, pot: 93 },
    { n: 'Franz Wagner', pos: 'SF', ovr: 85, age: 23, pot: 90 },
    { n: 'Jalen Suggs', pos: 'PG', ovr: 81, age: 23 },
    { n: 'Wendell Carter Jr.', pos: 'C', ovr: 79, age: 25 },
    { n: 'Kentavious Caldwell-Pope', pos: 'SG', ovr: 79, age: 31 },
    { n: 'Jonathan Isaac', pos: 'PF', ovr: 78, age: 27 },
    { n: 'Cole Anthony', pos: 'PG', ovr: 77, age: 24 },
    { n: 'Anthony Black', pos: 'SG', ovr: 74, age: 21, pot: 83 },
  ],
  WAS: [
    { n: 'Jordan Poole', pos: 'SG', ovr: 80, age: 25 },
    { n: 'Kyle Kuzma', pos: 'PF', ovr: 81, age: 29 },
    { n: 'Jonas Valanciunas', pos: 'C', ovr: 78, age: 32 },
    { n: 'Bilal Coulibaly', pos: 'SF', ovr: 77, age: 20, pot: 87 },
    { n: 'Malcolm Brogdon', pos: 'PG', ovr: 78, age: 32 },
    { n: 'Corey Kispert', pos: 'SF', ovr: 76, age: 25 },
    { n: 'Alex Sarr', pos: 'C', ovr: 76, age: 19, pot: 88 },
    { n: 'Bub Carrington', pos: 'PG', ovr: 73, age: 19, pot: 83 },
  ],
  /* ------------------------------ OUEST --------------------------------- */
  DEN: [
    { n: 'Nikola Jokic', pos: 'C', ovr: 98, age: 30 },
    { n: 'Jamal Murray', pos: 'PG', ovr: 86, age: 28 },
    { n: 'Aaron Gordon', pos: 'PF', ovr: 84, age: 29 },
    { n: 'Michael Porter Jr.', pos: 'SF', ovr: 83, age: 26 },
    { n: 'Russell Westbrook', pos: 'PG', ovr: 78, age: 36 },
    { n: 'Christian Braun', pos: 'SG', ovr: 78, age: 23 },
    { n: 'Peyton Watson', pos: 'SF', ovr: 76, age: 22, pot: 84 },
    { n: 'Julian Strawther', pos: 'SG', ovr: 73, age: 23 },
  ],
  MIN: [
    { n: 'Anthony Edwards', pos: 'SG', ovr: 92, age: 23, pot: 96 },
    { n: 'Rudy Gobert', pos: 'C', ovr: 85, age: 32 },
    { n: 'Julius Randle', pos: 'PF', ovr: 84, age: 30 },
    { n: 'Jaden McDaniels', pos: 'SF', ovr: 81, age: 24 },
    { n: 'Naz Reid', pos: 'C', ovr: 81, age: 25 },
    { n: 'Donte DiVincenzo', pos: 'SG', ovr: 80, age: 28 },
    { n: 'Mike Conley', pos: 'PG', ovr: 78, age: 37 },
    { n: 'Nickeil Alexander-Walker', pos: 'SG', ovr: 77, age: 26 },
  ],
  OKC: [
    { n: 'Shai Gilgeous-Alexander', pos: 'SG', ovr: 95, age: 26 },
    { n: 'Chet Holmgren', pos: 'C', ovr: 85, age: 22, pot: 92 },
    { n: 'Jalen Williams', pos: 'SF', ovr: 84, age: 23, pot: 90 },
    { n: 'Isaiah Hartenstein', pos: 'C', ovr: 80, age: 26 },
    { n: 'Luguentz Dort', pos: 'SG', ovr: 79, age: 25 },
    { n: 'Alex Caruso', pos: 'SG', ovr: 79, age: 31 },
    { n: 'Cason Wallace', pos: 'PG', ovr: 76, age: 21, pot: 84 },
    { n: 'Aaron Wiggins', pos: 'SG', ovr: 76, age: 26 },
  ],
  POR: [
    { n: 'Anfernee Simons', pos: 'SG', ovr: 82, age: 25 },
    { n: 'Jerami Grant', pos: 'SF', ovr: 80, age: 30 },
    { n: 'Deandre Ayton', pos: 'C', ovr: 81, age: 26 },
    { n: 'Shaedon Sharpe', pos: 'SG', ovr: 78, age: 21, pot: 87 },
    { n: 'Scoot Henderson', pos: 'PG', ovr: 77, age: 21, pot: 88 },
    { n: 'Toumani Camara', pos: 'SF', ovr: 76, age: 24 },
    { n: 'Robert Williams III', pos: 'C', ovr: 77, age: 27 },
    { n: 'Donovan Clingan', pos: 'C', ovr: 75, age: 21, pot: 85 },
  ],
  UTA: [
    { n: 'Lauri Markkanen', pos: 'PF', ovr: 85, age: 27 },
    { n: 'John Collins', pos: 'PF', ovr: 80, age: 27 },
    { n: 'Collin Sexton', pos: 'PG', ovr: 80, age: 26 },
    { n: 'Walker Kessler', pos: 'C', ovr: 79, age: 23 },
    { n: 'Jordan Clarkson', pos: 'SG', ovr: 78, age: 32 },
    { n: 'Keyonte George', pos: 'PG', ovr: 77, age: 21, pot: 85 },
    { n: 'Taylor Hendricks', pos: 'PF', ovr: 73, age: 21, pot: 83 },
    { n: 'Isaiah Collier', pos: 'PG', ovr: 72, age: 20, pot: 83 },
  ],
  GSW: [
    { n: 'Stephen Curry', pos: 'PG', ovr: 94, age: 37 },
    { n: 'Draymond Green', pos: 'PF', ovr: 82, age: 35 },
    { n: 'Andrew Wiggins', pos: 'SF', ovr: 81, age: 30 },
    { n: 'Jonathan Kuminga', pos: 'PF', ovr: 81, age: 22, pot: 89 },
    { n: 'Buddy Hield', pos: 'SG', ovr: 79, age: 32 },
    { n: 'Brandin Podziemski', pos: 'SG', ovr: 78, age: 22, pot: 85 },
    { n: "De'Anthony Melton", pos: 'SG', ovr: 76, age: 26 },
    { n: 'Kevon Looney', pos: 'C', ovr: 75, age: 29 },
  ],
  LAC: [
    { n: 'Kawhi Leonard', pos: 'SF', ovr: 90, age: 33 },
    { n: 'James Harden', pos: 'PG', ovr: 86, age: 35 },
    { n: 'Norman Powell', pos: 'SG', ovr: 82, age: 31 },
    { n: 'Ivica Zubac', pos: 'C', ovr: 82, age: 27 },
    { n: 'Terance Mann', pos: 'SG', ovr: 76, age: 28 },
    { n: 'Derrick Jones Jr.', pos: 'SF', ovr: 76, age: 27 },
    { n: 'Kris Dunn', pos: 'PG', ovr: 75, age: 30 },
    { n: 'Amir Coffey', pos: 'SG', ovr: 73, age: 27 },
  ],
  LAL: [
    { n: 'LeBron James', pos: 'SF', ovr: 93, age: 40 },
    { n: 'Anthony Davis', pos: 'C', ovr: 94, age: 31 },
    { n: 'Austin Reaves', pos: 'SG', ovr: 83, age: 26 },
    { n: "D'Angelo Russell", pos: 'PG', ovr: 80, age: 29 },
    { n: 'Rui Hachimura', pos: 'PF', ovr: 79, age: 27 },
    { n: 'Jarred Vanderbilt', pos: 'PF', ovr: 75, age: 25 },
    { n: 'Gabe Vincent', pos: 'PG', ovr: 74, age: 28 },
    { n: 'Dalton Knecht', pos: 'SG', ovr: 75, age: 23, pot: 83 },
  ],
  PHX: [
    { n: 'Kevin Durant', pos: 'SF', ovr: 94, age: 36 },
    { n: 'Devin Booker', pos: 'SG', ovr: 91, age: 28 },
    { n: 'Bradley Beal', pos: 'SG', ovr: 83, age: 31 },
    { n: 'Jusuf Nurkic', pos: 'C', ovr: 78, age: 30 },
    { n: 'Tyus Jones', pos: 'PG', ovr: 79, age: 28 },
    { n: 'Grayson Allen', pos: 'SG', ovr: 78, age: 29 },
    { n: 'Royce ONeale', pos: 'SF', ovr: 76, age: 31 },
    { n: 'Bol Bol', pos: 'C', ovr: 73, age: 25 },
  ],
  SAC: [
    { n: "De'Aaron Fox", pos: 'PG', ovr: 89, age: 27 },
    { n: 'Domantas Sabonis', pos: 'C', ovr: 88, age: 28 },
    { n: 'DeMar DeRozan', pos: 'SF', ovr: 83, age: 35 },
    { n: 'Keegan Murray', pos: 'SF', ovr: 81, age: 24 },
    { n: 'Malik Monk', pos: 'SG', ovr: 80, age: 27 },
    { n: 'Kevin Huerter', pos: 'SG', ovr: 77, age: 26 },
    { n: 'Trey Lyles', pos: 'PF', ovr: 74, age: 29 },
    { n: 'Keon Ellis', pos: 'SG', ovr: 74, age: 25 },
  ],
  DAL: [
    { n: 'Luka Doncic', pos: 'PG', ovr: 95, age: 26 },
    { n: 'Kyrie Irving', pos: 'PG', ovr: 89, age: 32 },
    { n: 'Klay Thompson', pos: 'SG', ovr: 81, age: 35 },
    { n: 'Daniel Gafford', pos: 'C', ovr: 80, age: 26 },
    { n: 'Dereck Lively II', pos: 'C', ovr: 79, age: 21, pot: 87 },
    { n: 'P.J. Washington', pos: 'PF', ovr: 79, age: 26 },
    { n: 'Naji Marshall', pos: 'SF', ovr: 76, age: 27 },
    { n: 'Spencer Dinwiddie', pos: 'PG', ovr: 76, age: 31 },
  ],
  HOU: [
    { n: 'Alperen Sengun', pos: 'C', ovr: 85, age: 22, pot: 91 },
    { n: 'Jalen Green', pos: 'SG', ovr: 82, age: 23, pot: 89 },
    { n: 'Fred VanVleet', pos: 'PG', ovr: 82, age: 30 },
    { n: 'Amen Thompson', pos: 'SF', ovr: 81, age: 22, pot: 90 },
    { n: 'Jabari Smith Jr.', pos: 'PF', ovr: 80, age: 21, pot: 88 },
    { n: 'Dillon Brooks', pos: 'SF', ovr: 78, age: 29 },
    { n: 'Tari Eason', pos: 'SF', ovr: 77, age: 23, pot: 85 },
    { n: 'Steven Adams', pos: 'C', ovr: 76, age: 31 },
  ],
  MEM: [
    { n: 'Ja Morant', pos: 'PG', ovr: 89, age: 25, pot: 92 },
    { n: 'Jaren Jackson Jr.', pos: 'PF', ovr: 86, age: 25 },
    { n: 'Desmond Bane', pos: 'SG', ovr: 83, age: 26 },
    { n: 'Marcus Smart', pos: 'PG', ovr: 78, age: 31 },
    { n: 'Santi Aldama', pos: 'PF', ovr: 77, age: 24 },
    { n: 'Zach Edey', pos: 'C', ovr: 76, age: 22, pot: 84 },
    { n: 'GG Jackson', pos: 'SF', ovr: 74, age: 20, pot: 84 },
    { n: 'Jaylen Wells', pos: 'SF', ovr: 73, age: 21, pot: 82 },
  ],
  NOP: [
    { n: 'Zion Williamson', pos: 'PF', ovr: 87, age: 24, pot: 92 },
    { n: 'Brandon Ingram', pos: 'SF', ovr: 85, age: 27 },
    { n: 'Dejounte Murray', pos: 'PG', ovr: 83, age: 28 },
    { n: 'CJ McCollum', pos: 'SG', ovr: 82, age: 33 },
    { n: 'Trey Murphy III', pos: 'SF', ovr: 80, age: 24 },
    { n: 'Herbert Jones', pos: 'SF', ovr: 79, age: 26 },
    { n: 'Jose Alvarado', pos: 'PG', ovr: 75, age: 26 },
    { n: 'Yves Missi', pos: 'C', ovr: 73, age: 20, pot: 83 },
  ],
  SAS: [
    { n: 'Victor Wembanyama', pos: 'C', ovr: 93, age: 21, pot: 99 },
    { n: 'Devin Vassell', pos: 'SG', ovr: 82, age: 24 },
    { n: 'Chris Paul', pos: 'PG', ovr: 79, age: 39 },
    { n: 'Jeremy Sochan', pos: 'PF', ovr: 78, age: 21, pot: 86 },
    { n: 'Keldon Johnson', pos: 'SF', ovr: 78, age: 25 },
    { n: 'Harrison Barnes', pos: 'SF', ovr: 77, age: 32 },
    { n: 'Stephon Castle', pos: 'SG', ovr: 76, age: 20, pot: 87 },
    { n: 'Julian Champagnie', pos: 'SF', ovr: 73, age: 23 },
  ],
};
