/* ==========================================================================
   NBA My Era — Effectifs (best-effort au 10/08/2026, saison 2026-27)
   --------------------------------------------------------------------------
   n = nom, pos = poste, ovr = note, age = âge (approx.), pot = potentiel (opt.)

   ⚠️  À VÉRIFIER — instantané reconstitué depuis des sources web. Le noyau de
   chaque équipe (titulaires + rotation) est fiable ; les joueurs de fond de banc
   sont best-effort et peuvent être datés. Tout est modifiable en jeu.
   Effectifs étoffés à ~13-15 joueurs réels par équipe (aucun nom généré).
   ========================================================================== */

const REAL_ROSTERS = {
  /* ------------------------------- EST ---------------------------------- */
  BOS: [
    { n: 'Jayson Tatum', pos: 'SF', ovr: 93, age: 27 },
    { n: 'Paul George', pos: 'SG', ovr: 84, age: 35 },
    { n: 'Derrick White', pos: 'PG', ovr: 85, age: 31 },
    { n: 'Anfernee Simons', pos: 'SG', ovr: 81, age: 27 },
    { n: 'Payton Pritchard', pos: 'PG', ovr: 81, age: 28 },
    { n: 'Neemias Queta', pos: 'C', ovr: 77, age: 26 },
    { n: 'Sam Hauser', pos: 'SF', ovr: 76, age: 28 },
    { n: 'Torrey Craig', pos: 'SF', ovr: 71, age: 35 },
    { n: 'Xavier Tillman', pos: 'C', ovr: 71, age: 27 },
    { n: 'Josh Minott', pos: 'PF', ovr: 70, age: 23, pot: 80 },
    { n: 'Jordan Walsh', pos: 'SF', ovr: 70, age: 22, pot: 80 },
    { n: 'JD Davison', pos: 'PG', ovr: 69, age: 23 },
    { n: 'Baylor Scheierman', pos: 'SG', ovr: 72, age: 25, pot: 80 },
  ],
  BKN: [
    { n: 'Michael Porter Jr.', pos: 'SF', ovr: 82, age: 27 },
    { n: 'Julius Randle', pos: 'PF', ovr: 83, age: 31 },
    { n: 'Cam Thomas', pos: 'SG', ovr: 81, age: 24 },
    { n: 'Terance Mann', pos: 'SG', ovr: 75, age: 29 },
    { n: 'Egor Demin', pos: 'PG', ovr: 74, age: 20, pot: 85 },
    { n: "Day'Ron Sharpe", pos: 'C', ovr: 74, age: 24 },
    { n: 'Noah Clowney', pos: 'PF', ovr: 74, age: 21, pot: 83 },
    { n: 'Ziaire Williams', pos: 'SF', ovr: 74, age: 24 },
    { n: 'Drew Timme', pos: 'C', ovr: 71, age: 25 },
    { n: 'Tyrese Martin', pos: 'SG', ovr: 70, age: 26 },
    { n: 'Dariq Whitehead', pos: 'SG', ovr: 70, age: 21, pot: 82 },
    { n: 'Tosan Evbuomwan', pos: 'SF', ovr: 69, age: 24 },
    { n: 'Keon Johnson', pos: 'SG', ovr: 71, age: 23 },
  ],
  NYK: [
    { n: 'Jalen Brunson', pos: 'PG', ovr: 91, age: 29 },
    { n: 'Karl-Anthony Towns', pos: 'C', ovr: 88, age: 30 },
    { n: 'Mikal Bridges', pos: 'SF', ovr: 85, age: 29 },
    { n: 'OG Anunoby', pos: 'SF', ovr: 84, age: 28 },
    { n: 'Josh Hart', pos: 'SG', ovr: 82, age: 30 },
    { n: 'Mitchell Robinson', pos: 'C', ovr: 79, age: 27 },
    { n: 'Miles McBride', pos: 'PG', ovr: 76, age: 25 },
    { n: 'Guerschon Yabusele', pos: 'PF', ovr: 76, age: 30 },
    { n: 'Precious Achiuwa', pos: 'C', ovr: 74, age: 26 },
    { n: 'Landry Shamet', pos: 'SG', ovr: 72, age: 29 },
    { n: 'Tyler Kolek', pos: 'PG', ovr: 70, age: 24, pot: 80 },
    { n: 'Pacome Dadiet', pos: 'SF', ovr: 69, age: 20, pot: 82 },
    { n: 'Ariel Hukporti', pos: 'C', ovr: 69, age: 23, pot: 79 },
  ],
  PHI: [
    { n: 'Joel Embiid', pos: 'C', ovr: 93, age: 32 },
    { n: 'Tyrese Maxey', pos: 'PG', ovr: 90, age: 25 },
    { n: 'Jaylen Brown', pos: 'SG', ovr: 89, age: 29 },
    { n: 'LeBron James', pos: 'PF', ovr: 88, age: 41 },
    { n: 'VJ Edgecombe', pos: 'SG', ovr: 78, age: 20, pot: 89 },
    { n: 'Kelly Oubre Jr.', pos: 'SF', ovr: 79, age: 30 },
    { n: 'Jared McCain', pos: 'PG', ovr: 78, age: 22, pot: 86 },
    { n: 'Andre Drummond', pos: 'C', ovr: 75, age: 32 },
    { n: 'Adem Bona', pos: 'C', ovr: 73, age: 22, pot: 82 },
    { n: 'Justin Edwards', pos: 'SF', ovr: 71, age: 22, pot: 81 },
    { n: 'Ricky Council IV', pos: 'SG', ovr: 71, age: 24 },
    { n: 'KJ Martin', pos: 'PF', ovr: 71, age: 25 },
    { n: 'Jeff Dowtin Jr.', pos: 'PG', ovr: 68, age: 28 },
  ],
  TOR: [
    { n: 'Scottie Barnes', pos: 'PF', ovr: 86, age: 24, pot: 92 },
    { n: 'Brandon Ingram', pos: 'SF', ovr: 84, age: 29 },
    { n: 'RJ Barrett', pos: 'SG', ovr: 83, age: 25 },
    { n: 'Immanuel Quickley', pos: 'PG', ovr: 81, age: 26 },
    { n: 'Jakob Poeltl', pos: 'C', ovr: 80, age: 30 },
    { n: 'Gradey Dick', pos: 'SG', ovr: 77, age: 22, pot: 84 },
    { n: 'Ja\'Kobe Walter', pos: 'SG', ovr: 74, age: 21, pot: 83 },
    { n: 'Ochai Agbaji', pos: 'SG', ovr: 74, age: 25 },
    { n: 'Chris Boucher', pos: 'PF', ovr: 74, age: 33 },
    { n: 'Jonathan Mogbo', pos: 'PF', ovr: 71, age: 24, pot: 80 },
    { n: 'Jamal Shead', pos: 'PG', ovr: 72, age: 23, pot: 80 },
    { n: 'Jamison Battle', pos: 'SF', ovr: 69, age: 24 },
    { n: 'Collin Murray-Boyles', pos: 'PF', ovr: 71, age: 20, pot: 84 },
  ],
  CHI: [
    { n: 'Josh Giddey', pos: 'PG', ovr: 82, age: 23 },
    { n: 'Coby White', pos: 'SG', ovr: 82, age: 26 },
    { n: 'Nic Claxton', pos: 'C', ovr: 81, age: 26 },
    { n: 'Norman Powell', pos: 'SG', ovr: 81, age: 33 },
    { n: 'Matas Buzelis', pos: 'PF', ovr: 79, age: 21, pot: 88 },
    { n: 'Ayo Dosunmu', pos: 'SG', ovr: 77, age: 26 },
    { n: 'Kevin Huerter', pos: 'SF', ovr: 75, age: 27 },
    { n: 'Patrick Williams', pos: 'PF', ovr: 75, age: 24 },
    { n: 'Noa Essengue', pos: 'PF', ovr: 72, age: 19, pot: 84 },
    { n: 'Jalen Smith', pos: 'C', ovr: 74, age: 26 },
    { n: 'Talen Horton-Tucker', pos: 'SG', ovr: 72, age: 25 },
    { n: 'Dalen Terry', pos: 'SG', ovr: 70, age: 24 },
    { n: 'Julian Phillips', pos: 'SF', ovr: 69, age: 22, pot: 79 },
  ],
  CLE: [
    { n: 'Donovan Mitchell', pos: 'SG', ovr: 92, age: 29 },
    { n: 'Evan Mobley', pos: 'PF', ovr: 89, age: 24, pot: 94 },
    { n: 'Jarrett Allen', pos: 'C', ovr: 84, age: 28 },
    { n: 'De\'Andre Hunter', pos: 'SF', ovr: 79, age: 28 },
    { n: 'Max Strus', pos: 'SF', ovr: 78, age: 30 },
    { n: 'Ty Jerome', pos: 'PG', ovr: 78, age: 28 },
    { n: 'Sam Merrill', pos: 'SG', ovr: 75, age: 30 },
    { n: 'Dean Wade', pos: 'PF', ovr: 72, age: 29 },
    { n: 'Georges Niang', pos: 'PF', ovr: 73, age: 32 },
    { n: 'Jaylon Tyson', pos: 'SG', ovr: 71, age: 23, pot: 81 },
    { n: 'Craig Porter Jr.', pos: 'PG', ovr: 71, age: 25 },
    { n: 'Isaiah Mobley', pos: 'C', ovr: 68, age: 26 },
    { n: 'Tristan Thompson', pos: 'C', ovr: 68, age: 34 },
  ],
  DET: [
    { n: 'Cade Cunningham', pos: 'PG', ovr: 90, age: 24, pot: 94 },
    { n: 'Jalen Duren', pos: 'C', ovr: 82, age: 22, pot: 87 },
    { n: 'Ausar Thompson', pos: 'SF', ovr: 80, age: 23, pot: 88 },
    { n: 'Jaden Ivey', pos: 'SG', ovr: 80, age: 23 },
    { n: 'Tobias Harris', pos: 'SF', ovr: 78, age: 33 },
    { n: 'Isaiah Stewart', pos: 'C', ovr: 77, age: 24 },
    { n: 'Duncan Robinson', pos: 'SF', ovr: 77, age: 32 },
    { n: 'Marcus Sasser', pos: 'PG', ovr: 74, age: 24 },
    { n: 'Simone Fontecchio', pos: 'SF', ovr: 73, age: 30 },
    { n: 'Ronald Holland II', pos: 'SF', ovr: 72, age: 20, pot: 84 },
    { n: 'Paul Reed', pos: 'C', ovr: 71, age: 27 },
    { n: 'Bobi Klintman', pos: 'PF', ovr: 68, age: 23, pot: 79 },
    { n: 'Wendell Moore Jr.', pos: 'SG', ovr: 68, age: 24 },
  ],
  IND: [
    { n: 'Tyrese Haliburton', pos: 'PG', ovr: 89, age: 25 },
    { n: 'Pascal Siakam', pos: 'PF', ovr: 87, age: 31 },
    { n: 'Bennedict Mathurin', pos: 'SG', ovr: 81, age: 23, pot: 87 },
    { n: 'Andrew Nembhard', pos: 'PG', ovr: 78, age: 25 },
    { n: 'Aaron Nesmith', pos: 'SF', ovr: 78, age: 26 },
    { n: 'Obi Toppin', pos: 'PF', ovr: 77, age: 27 },
    { n: 'T.J. McConnell', pos: 'PG', ovr: 76, age: 33 },
    { n: 'Isaiah Jackson', pos: 'C', ovr: 76, age: 24 },
    { n: 'Jarace Walker', pos: 'PF', ovr: 75, age: 22, pot: 84 },
    { n: 'Ben Sheppard', pos: 'SG', ovr: 72, age: 24 },
    { n: 'James Wiseman', pos: 'C', ovr: 71, age: 25 },
    { n: 'Johnny Furphy', pos: 'SF', ovr: 70, age: 21, pot: 82 },
    { n: 'Tony Bradley', pos: 'C', ovr: 68, age: 28 },
  ],
  MIL: [
    { n: 'Tyler Herro', pos: 'SG', ovr: 85, age: 26 },
    { n: 'Myles Turner', pos: 'C', ovr: 82, age: 29 },
    { n: 'Kyle Kuzma', pos: 'PF', ovr: 80, age: 30 },
    { n: 'Kevin Porter Jr.', pos: 'PG', ovr: 76, age: 25 },
    { n: 'Kel\'el Ware', pos: 'C', ovr: 79, age: 22, pot: 88 },
    { n: 'Jaime Jaquez Jr.', pos: 'SF', ovr: 78, age: 25 },
    { n: 'Gary Trent Jr.', pos: 'SG', ovr: 77, age: 27 },
    { n: 'Kasparas Jakucionis', pos: 'PG', ovr: 74, age: 20, pot: 84 },
    { n: 'Taurean Prince', pos: 'SF', ovr: 72, age: 31 },
    { n: 'AJ Green', pos: 'SG', ovr: 74, age: 26 },
    { n: 'Andre Jackson Jr.', pos: 'SG', ovr: 70, age: 24 },
    { n: 'Pat Connaughton', pos: 'SG', ovr: 71, age: 33 },
    { n: 'Chris Livingston', pos: 'SF', ovr: 68, age: 22 },
  ],
  ATL: [
    { n: 'Trae Young', pos: 'PG', ovr: 88, age: 27 },
    { n: 'Jalen Johnson', pos: 'PF', ovr: 84, age: 24, pot: 89 },
    { n: 'Kristaps Porzingis', pos: 'C', ovr: 83, age: 30 },
    { n: 'Dyson Daniels', pos: 'SG', ovr: 81, age: 23, pot: 86 },
    { n: 'Caris LeVert', pos: 'SG', ovr: 77, age: 31 },
    { n: 'Lu Dort', pos: 'SG', ovr: 79, age: 26 },
    { n: 'Onyeka Okongwu', pos: 'C', ovr: 80, age: 25 },
    { n: 'Zaccharie Risacher', pos: 'SF', ovr: 78, age: 20, pot: 88 },
    { n: 'Nickeil Alexander-Walker', pos: 'SG', ovr: 77, age: 27 },
    { n: 'Larry Nance Jr.', pos: 'PF', ovr: 72, age: 33 },
    { n: 'Vit Krejci', pos: 'SG', ovr: 71, age: 26 },
    { n: 'Mouhamed Gueye', pos: 'PF', ovr: 69, age: 23, pot: 79 },
    { n: 'Asa Newell', pos: 'PF', ovr: 71, age: 20, pot: 83 },
  ],
  CHA: [
    { n: 'Brandon Miller', pos: 'SF', ovr: 82, age: 23, pot: 89 },
    { n: 'Collin Sexton', pos: 'PG', ovr: 79, age: 27 },
    { n: 'Kon Knueppel', pos: 'SG', ovr: 77, age: 20, pot: 86 },
    { n: 'Grant Williams', pos: 'PF', ovr: 76, age: 27 },
    { n: 'Tre Mann', pos: 'PG', ovr: 76, age: 24 },
    { n: 'Josh Green', pos: 'SG', ovr: 75, age: 25 },
    { n: 'Moussa Diabaté', pos: 'C', ovr: 74, age: 24 },
    { n: 'Tidjane Salaun', pos: 'PF', ovr: 74, age: 20, pot: 84 },
    { n: 'Ryan Kalkbrenner', pos: 'C', ovr: 72, age: 23, pot: 81 },
    { n: 'Josh Okogie', pos: 'SG', ovr: 71, age: 27 },
    { n: 'Liam McNeeley', pos: 'SF', ovr: 71, age: 20, pot: 83 },
    { n: 'KJ Simpson', pos: 'PG', ovr: 68, age: 23 },
    { n: 'Sion James', pos: 'SG', ovr: 68, age: 23, pot: 78 },
  ],
  MIA: [
    { n: 'Giannis Antetokounmpo', pos: 'PF', ovr: 96, age: 31 },
    { n: 'Bam Adebayo', pos: 'C', ovr: 88, age: 28 },
    { n: 'Andrew Wiggins', pos: 'SF', ovr: 81, age: 30 },
    { n: 'Bobby Portis', pos: 'PF', ovr: 80, age: 30 },
    { n: 'Davion Mitchell', pos: 'PG', ovr: 78, age: 27 },
    { n: 'Terry Rozier', pos: 'PG', ovr: 77, age: 31 },
    { n: 'Nikola Jovic', pos: 'SF', ovr: 77, age: 22, pot: 85 },
    { n: 'Tim Hardaway Jr.', pos: 'SG', ovr: 76, age: 33 },
    { n: 'Kevin Love', pos: 'PF', ovr: 72, age: 37 },
    { n: 'Haywood Highsmith', pos: 'SF', ovr: 72, age: 29 },
    { n: 'Pelle Larsson', pos: 'SG', ovr: 73, age: 24 },
    { n: 'Keshad Johnson', pos: 'PF', ovr: 68, age: 24 },
    { n: 'Josh Richardson', pos: 'SG', ovr: 71, age: 32 },
  ],
  ORL: [
    { n: 'Paolo Banchero', pos: 'PF', ovr: 88, age: 22, pot: 93 },
    { n: 'Franz Wagner', pos: 'SF', ovr: 86, age: 24, pot: 90 },
    { n: 'Desmond Bane', pos: 'SG', ovr: 84, age: 27 },
    { n: 'Jalen Suggs', pos: 'PG', ovr: 81, age: 24 },
    { n: 'Wendell Carter Jr.', pos: 'C', ovr: 79, age: 26 },
    { n: 'Jonathan Isaac', pos: 'PF', ovr: 78, age: 28 },
    { n: 'Cole Anthony', pos: 'PG', ovr: 76, age: 25 },
    { n: 'Anthony Black', pos: 'SG', ovr: 75, age: 21, pot: 84 },
    { n: 'Tristan da Silva', pos: 'SF', ovr: 75, age: 24 },
    { n: 'Goga Bitadze', pos: 'C', ovr: 74, age: 26 },
    { n: 'Jett Howard', pos: 'SG', ovr: 70, age: 22, pot: 80 },
    { n: 'Gary Harris', pos: 'SG', ovr: 71, age: 31 },
    { n: 'Jase Richardson', pos: 'PG', ovr: 71, age: 19, pot: 84 },
  ],
  WAS: [
    { n: 'AJ Dybantsa', pos: 'SF', ovr: 78, age: 19, pot: 93 },
    { n: 'CJ McCollum', pos: 'SG', ovr: 79, age: 34 },
    { n: 'Khris Middleton', pos: 'SF', ovr: 78, age: 34 },
    { n: 'Deandre Ayton', pos: 'C', ovr: 80, age: 27 },
    { n: 'Alex Sarr', pos: 'C', ovr: 78, age: 20, pot: 88 },
    { n: 'Bilal Coulibaly', pos: 'SF', ovr: 78, age: 21, pot: 87 },
    { n: 'Bub Carrington', pos: 'PG', ovr: 76, age: 20, pot: 84 },
    { n: 'Tre Johnson', pos: 'SG', ovr: 75, age: 19, pot: 86 },
    { n: 'Kyshawn George', pos: 'SF', ovr: 74, age: 21, pot: 83 },
    { n: 'Corey Kispert', pos: 'SF', ovr: 74, age: 26 },
    { n: 'Saddiq Bey', pos: 'SF', ovr: 73, age: 27 },
    { n: 'Marvin Bagley III', pos: 'C', ovr: 71, age: 27 },
    { n: 'Richaun Holmes', pos: 'C', ovr: 70, age: 32 },
  ],
  /* ------------------------------ OUEST --------------------------------- */
  DEN: [
    { n: 'Nikola Jokic', pos: 'C', ovr: 98, age: 30 },
    { n: 'Jamal Murray', pos: 'PG', ovr: 86, age: 28 },
    { n: 'Aaron Gordon', pos: 'PF', ovr: 84, age: 30 },
    { n: 'Cam Johnson', pos: 'SF', ovr: 82, age: 30 },
    { n: 'Christian Braun', pos: 'SG', ovr: 79, age: 24 },
    { n: 'Jonas Valanciunas', pos: 'C', ovr: 78, age: 34 },
    { n: 'Peyton Watson', pos: 'SF', ovr: 77, age: 23, pot: 84 },
    { n: 'Julian Strawther', pos: 'SG', ovr: 74, age: 23 },
    { n: 'DaRon Holmes II', pos: 'C', ovr: 71, age: 22, pot: 83 },
    { n: 'Zeke Nnaji', pos: 'PF', ovr: 68, age: 25 },
    { n: 'Hunter Tyson', pos: 'SF', ovr: 69, age: 25 },
    { n: 'Spencer Jones', pos: 'SF', ovr: 68, age: 24 },
    { n: 'Dario Saric', pos: 'PF', ovr: 70, age: 32 },
  ],
  MIN: [
    { n: 'Anthony Edwards', pos: 'SG', ovr: 93, age: 24, pot: 96 },
    { n: 'LaMelo Ball', pos: 'PG', ovr: 86, age: 24, pot: 91 },
    { n: 'Rudy Gobert', pos: 'C', ovr: 85, age: 33 },
    { n: 'Jaden McDaniels', pos: 'SF', ovr: 82, age: 25 },
    { n: 'Naz Reid', pos: 'C', ovr: 81, age: 26 },
    { n: 'Donte DiVincenzo', pos: 'SG', ovr: 80, age: 29 },
    { n: 'Mike Conley', pos: 'PG', ovr: 76, age: 38 },
    { n: 'Terrence Shannon Jr.', pos: 'SG', ovr: 76, age: 25 },
    { n: 'Rob Dillingham', pos: 'PG', ovr: 75, age: 21, pot: 85 },
    { n: 'Jaylen Clark', pos: 'SG', ovr: 70, age: 24 },
    { n: 'Luka Garza', pos: 'C', ovr: 70, age: 27 },
    { n: 'Leonard Miller', pos: 'PF', ovr: 70, age: 22, pot: 81 },
    { n: 'Joan Beringer', pos: 'C', ovr: 70, age: 19, pot: 84 },
  ],
  OKC: [
    { n: 'Shai Gilgeous-Alexander', pos: 'SG', ovr: 98, age: 27 },
    { n: 'Chet Holmgren', pos: 'C', ovr: 88, age: 23, pot: 93 },
    { n: 'Jalen Williams', pos: 'SF', ovr: 87, age: 24, pot: 91 },
    { n: 'Isaiah Hartenstein', pos: 'C', ovr: 80, age: 27 },
    { n: 'Alex Caruso', pos: 'SG', ovr: 79, age: 32 },
    { n: 'Cason Wallace', pos: 'PG', ovr: 77, age: 22, pot: 85 },
    { n: 'Aaron Wiggins', pos: 'SG', ovr: 76, age: 27 },
    { n: 'Isaiah Joe', pos: 'SG', ovr: 75, age: 26 },
    { n: 'Kenrich Williams', pos: 'SF', ovr: 71, age: 31 },
    { n: 'Jaylin Williams', pos: 'C', ovr: 71, age: 23 },
    { n: 'Ousmane Dieng', pos: 'SF', ovr: 70, age: 22, pot: 80 },
    { n: 'Nikola Topic', pos: 'PG', ovr: 71, age: 20, pot: 84 },
    { n: 'Thomas Sorber', pos: 'C', ovr: 71, age: 20, pot: 83 },
  ],
  POR: [
    { n: 'Ja Morant', pos: 'PG', ovr: 88, age: 26, pot: 91 },
    { n: 'Deni Avdija', pos: 'SF', ovr: 82, age: 25 },
    { n: 'Jrue Holiday', pos: 'PG', ovr: 82, age: 35 },
    { n: 'Jerami Grant', pos: 'SF', ovr: 79, age: 31 },
    { n: 'Shaedon Sharpe', pos: 'SG', ovr: 79, age: 22, pot: 87 },
    { n: 'Toumani Camara', pos: 'SF', ovr: 77, age: 25 },
    { n: 'Donovan Clingan', pos: 'C', ovr: 77, age: 22, pot: 86 },
    { n: 'Scoot Henderson', pos: 'PG', ovr: 76, age: 22, pot: 85 },
    { n: 'Robert Williams III', pos: 'C', ovr: 76, age: 28 },
    { n: 'Matisse Thybulle', pos: 'SF', ovr: 72, age: 29 },
    { n: 'Kris Murray', pos: 'SF', ovr: 70, age: 25 },
    { n: 'Duop Reath', pos: 'C', ovr: 70, age: 29 },
    { n: 'Rayan Rupert', pos: 'SG', ovr: 68, age: 22, pot: 79 },
  ],
  UTA: [
    { n: 'Lauri Markkanen', pos: 'PF', ovr: 85, age: 28 },
    { n: 'John Collins', pos: 'PF', ovr: 80, age: 28 },
    { n: 'Keyonte George', pos: 'PG', ovr: 78, age: 22, pot: 86 },
    { n: 'Ace Bailey', pos: 'SF', ovr: 77, age: 19, pot: 89 },
    { n: 'Isaiah Collier', pos: 'PG', ovr: 75, age: 21, pot: 84 },
    { n: 'Taylor Hendricks', pos: 'PF', ovr: 75, age: 22, pot: 84 },
    { n: 'Brice Sensabaugh', pos: 'SF', ovr: 72, age: 22, pot: 81 },
    { n: 'Cody Williams', pos: 'SF', ovr: 71, age: 21, pot: 83 },
    { n: 'Jusuf Nurkic', pos: 'C', ovr: 75, age: 31 },
    { n: 'Kyle Filipowski', pos: 'C', ovr: 74, age: 22, pot: 84 },
    { n: 'Svi Mykhailiuk', pos: 'SG', ovr: 71, age: 29 },
    { n: 'Walter Clayton Jr.', pos: 'PG', ovr: 72, age: 23, pot: 82 },
    { n: 'Johnny Juzang', pos: 'SG', ovr: 69, age: 25 },
  ],
  GSW: [
    { n: 'Stephen Curry', pos: 'PG', ovr: 93, age: 37 },
    { n: 'Jimmy Butler', pos: 'SF', ovr: 87, age: 36 },
    { n: 'Draymond Green', pos: 'PF', ovr: 81, age: 35 },
    { n: 'Jonathan Kuminga', pos: 'PF', ovr: 80, age: 22, pot: 88 },
    { n: 'Brandin Podziemski', pos: 'SG', ovr: 79, age: 22, pot: 85 },
    { n: 'Buddy Hield', pos: 'SG', ovr: 78, age: 32 },
    { n: 'Moses Moody', pos: 'SG', ovr: 77, age: 23 },
    { n: 'Kevon Looney', pos: 'C', ovr: 74, age: 29 },
    { n: 'Trayce Jackson-Davis', pos: 'C', ovr: 73, age: 25 },
    { n: 'Gui Santos', pos: 'SF', ovr: 71, age: 23, pot: 80 },
    { n: 'Quinten Post', pos: 'C', ovr: 73, age: 25 },
    { n: 'Gary Payton II', pos: 'SG', ovr: 72, age: 33 },
    { n: 'Pat Spencer', pos: 'PG', ovr: 66, age: 29 },
  ],
  LAC: [
    { n: 'Kawhi Leonard', pos: 'SF', ovr: 89, age: 34 },
    { n: 'James Harden', pos: 'PG', ovr: 85, age: 36 },
    { n: 'Darius Garland', pos: 'PG', ovr: 84, age: 26 },
    { n: 'Ivica Zubac', pos: 'C', ovr: 83, age: 28 },
    { n: 'Brook Lopez', pos: 'C', ovr: 78, age: 37 },
    { n: 'Bogdan Bogdanovic', pos: 'SG', ovr: 77, age: 33 },
    { n: 'Derrick Jones Jr.', pos: 'SF', ovr: 75, age: 28 },
    { n: 'Kris Dunn', pos: 'PG', ovr: 75, age: 31 },
    { n: 'Nicolas Batum', pos: 'SF', ovr: 73, age: 37 },
    { n: 'P.J. Tucker', pos: 'PF', ovr: 68, age: 40 },
    { n: 'Jordan Miller', pos: 'SF', ovr: 69, age: 25 },
    { n: 'Cam Christie', pos: 'SG', ovr: 68, age: 21, pot: 79 },
    { n: 'Kobe Brown', pos: 'SF', ovr: 67, age: 25 },
  ],
  LAL: [
    { n: 'Luka Doncic', pos: 'PG', ovr: 95, age: 26 },
    { n: 'Austin Reaves', pos: 'SG', ovr: 84, age: 27 },
    { n: 'Walker Kessler', pos: 'C', ovr: 80, age: 24 },
    { n: 'Rui Hachimura', pos: 'PF', ovr: 79, age: 28 },
    { n: 'Quentin Grimes', pos: 'SF', ovr: 78, age: 25 },
    { n: 'Gabe Vincent', pos: 'PG', ovr: 74, age: 28 },
    { n: 'Dalton Knecht', pos: 'SG', ovr: 76, age: 24, pot: 83 },
    { n: 'Jarred Vanderbilt', pos: 'PF', ovr: 75, age: 26 },
    { n: 'Jaxson Hayes', pos: 'C', ovr: 72, age: 25 },
    { n: 'Maxi Kleber', pos: 'PF', ovr: 70, age: 34 },
    { n: 'Bronny James', pos: 'SG', ovr: 66, age: 21, pot: 78 },
    { n: 'Jake LaRavia', pos: 'SF', ovr: 73, age: 24 },
    { n: 'Christian Koloko', pos: 'C', ovr: 68, age: 25 },
  ],
  PHX: [
    { n: 'Devin Booker', pos: 'SG', ovr: 91, age: 29 },
    { n: 'Jalen Green', pos: 'SG', ovr: 82, age: 24, pot: 89 },
    { n: 'Dillon Brooks', pos: 'SF', ovr: 78, age: 30 },
    { n: 'Mark Williams', pos: 'C', ovr: 79, age: 24, pot: 85 },
    { n: 'Grayson Allen', pos: 'SG', ovr: 78, age: 30 },
    { n: 'Royce ONeale', pos: 'SF', ovr: 76, age: 31 },
    { n: 'Nick Richards', pos: 'C', ovr: 75, age: 28 },
    { n: 'Ryan Dunn', pos: 'SF', ovr: 75, age: 22, pot: 84 },
    { n: 'Khaman Maluach', pos: 'C', ovr: 74, age: 19, pot: 87 },
    { n: 'Collin Gillespie', pos: 'PG', ovr: 74, age: 26 },
    { n: 'Oso Ighodaro', pos: 'C', ovr: 70, age: 23, pot: 80 },
    { n: 'Bol Bol', pos: 'C', ovr: 72, age: 25 },
    { n: 'TyTy Washington Jr.', pos: 'PG', ovr: 67, age: 24 },
  ],
  SAC: [
    { n: 'Domantas Sabonis', pos: 'C', ovr: 87, age: 29 },
    { n: 'Zach LaVine', pos: 'SG', ovr: 83, age: 31 },
    { n: 'DeMar DeRozan', pos: 'SF', ovr: 82, age: 36 },
    { n: 'Keegan Murray', pos: 'SF', ovr: 81, age: 25 },
    { n: 'Malik Monk', pos: 'SG', ovr: 79, age: 27 },
    { n: 'Devin Carter', pos: 'SG', ovr: 74, age: 23, pot: 83 },
    { n: 'Keon Ellis', pos: 'SG', ovr: 75, age: 25 },
    { n: 'Trey Lyles', pos: 'PF', ovr: 73, age: 30 },
    { n: 'Doug McDermott', pos: 'SF', ovr: 71, age: 34 },
    { n: 'Isaac Jones', pos: 'C', ovr: 69, age: 24 },
    { n: 'Maxime Raynaud', pos: 'C', ovr: 70, age: 22, pot: 82 },
    { n: 'Nique Clifford', pos: 'SG', ovr: 71, age: 23, pot: 82 },
    { n: 'Terence Davis', pos: 'SG', ovr: 68, age: 29 },
  ],
  DAL: [
    { n: 'Anthony Davis', pos: 'C', ovr: 93, age: 32 },
    { n: 'Cooper Flagg', pos: 'SF', ovr: 82, age: 19, pot: 96 },
    { n: 'Kyrie Irving', pos: 'PG', ovr: 88, age: 33 },
    { n: 'Klay Thompson', pos: 'SG', ovr: 80, age: 36 },
    { n: 'D\'Angelo Russell', pos: 'PG', ovr: 78, age: 30 },
    { n: 'Daniel Gafford', pos: 'C', ovr: 80, age: 27 },
    { n: 'Dereck Lively II', pos: 'C', ovr: 79, age: 22, pot: 87 },
    { n: 'P.J. Washington', pos: 'PF', ovr: 79, age: 27 },
    { n: 'Max Christie', pos: 'SG', ovr: 76, age: 23 },
    { n: 'Naji Marshall', pos: 'SF', ovr: 76, age: 28 },
    { n: 'Dante Exum', pos: 'PG', ovr: 71, age: 30 },
    { n: 'Jaden Hardy', pos: 'SG', ovr: 72, age: 23, pot: 81 },
    { n: 'Olivier-Maxence Prosper', pos: 'PF', ovr: 69, age: 23, pot: 80 },
  ],
  HOU: [
    { n: 'Kevin Durant', pos: 'SF', ovr: 93, age: 37 },
    { n: 'Alperen Sengun', pos: 'C', ovr: 86, age: 23, pot: 91 },
    { n: 'Amen Thompson', pos: 'SF', ovr: 82, age: 23, pot: 91 },
    { n: 'Fred VanVleet', pos: 'PG', ovr: 80, age: 32 },
    { n: 'Jabari Smith Jr.', pos: 'PF', ovr: 80, age: 22, pot: 88 },
    { n: 'Reed Sheppard', pos: 'PG', ovr: 78, age: 21, pot: 86 },
    { n: 'Tari Eason', pos: 'SF', ovr: 78, age: 24, pot: 85 },
    { n: 'Steven Adams', pos: 'C', ovr: 76, age: 32 },
    { n: 'Dorian Finney-Smith', pos: 'SF', ovr: 76, age: 33 },
    { n: 'Jae\'Sean Tate', pos: 'SF', ovr: 70, age: 30 },
    { n: 'Aaron Holiday', pos: 'PG', ovr: 71, age: 29 },
    { n: 'Jock Landale', pos: 'C', ovr: 71, age: 30 },
    { n: 'Cam Whitmore', pos: 'SF', ovr: 73, age: 21, pot: 83 },
  ],
  MEM: [
    { n: 'Jaren Jackson Jr.', pos: 'PF', ovr: 86, age: 26 },
    { n: 'Zach Edey', pos: 'C', ovr: 78, age: 23, pot: 85 },
    { n: 'Santi Aldama', pos: 'PF', ovr: 77, age: 25 },
    { n: 'Jaylen Wells', pos: 'SF', ovr: 76, age: 22, pot: 84 },
    { n: 'Scotty Pippen Jr.', pos: 'PG', ovr: 75, age: 25 },
    { n: 'GG Jackson', pos: 'SF', ovr: 75, age: 21, pot: 85 },
    { n: 'Luke Kennard', pos: 'SG', ovr: 73, age: 30 },
    { n: 'Brandon Clarke', pos: 'PF', ovr: 74, age: 29 },
    { n: 'John Konchar', pos: 'SG', ovr: 70, age: 30 },
    { n: 'Jay Huff', pos: 'C', ovr: 70, age: 28 },
    { n: 'Cedric Coward', pos: 'SG', ovr: 73, age: 22, pot: 84 },
    { n: 'Vince Williams Jr.', pos: 'SG', ovr: 73, age: 25 },
    { n: 'PJ Hall', pos: 'C', ovr: 67, age: 24 },
  ],
  NOP: [
    { n: 'Zion Williamson', pos: 'PF', ovr: 87, age: 25, pot: 91 },
    { n: 'Trey Murphy III', pos: 'SF', ovr: 82, age: 25 },
    { n: 'Dejounte Murray', pos: 'PG', ovr: 82, age: 28 },
    { n: 'Jordan Poole', pos: 'SG', ovr: 80, age: 26 },
    { n: 'Herbert Jones', pos: 'SF', ovr: 79, age: 26 },
    { n: 'Jose Alvarado', pos: 'PG', ovr: 75, age: 27 },
    { n: 'Yves Missi', pos: 'C', ovr: 75, age: 20, pot: 84 },
    { n: 'Jeremiah Fears', pos: 'PG', ovr: 74, age: 19, pot: 85 },
    { n: 'Derik Queen', pos: 'C', ovr: 74, age: 20, pot: 85 },
    { n: 'Jordan Hawkins', pos: 'SG', ovr: 73, age: 24 },
    { n: 'Karlo Matkovic', pos: 'PF', ovr: 70, age: 24 },
    { n: 'Antonio Reeves', pos: 'SG', ovr: 69, age: 24 },
    { n: 'Kevon Harris', pos: 'SF', ovr: 67, age: 28 },
  ],
  SAS: [
    { n: 'Victor Wembanyama', pos: 'C', ovr: 95, age: 21, pot: 99 },
    { n: 'De\'Aaron Fox', pos: 'PG', ovr: 88, age: 27 },
    { n: 'Devin Vassell', pos: 'SG', ovr: 81, age: 24 },
    { n: 'Stephon Castle', pos: 'SG', ovr: 80, age: 20, pot: 89 },
    { n: 'Dylan Harper', pos: 'SG', ovr: 78, age: 19, pot: 90 },
    { n: 'Jeremy Sochan', pos: 'PF', ovr: 78, age: 22, pot: 86 },
    { n: 'Keldon Johnson', pos: 'SF', ovr: 77, age: 25 },
    { n: 'Harrison Barnes', pos: 'SF', ovr: 76, age: 33 },
    { n: 'Luke Kornet', pos: 'C', ovr: 74, age: 30 },
    { n: 'Julian Champagnie', pos: 'SF', ovr: 72, age: 24 },
    { n: 'Malaki Branham', pos: 'SG', ovr: 70, age: 22, pot: 80 },
    { n: 'Blake Wesley', pos: 'PG', ovr: 69, age: 22, pot: 79 },
    { n: 'Charles Bassey', pos: 'C', ovr: 69, age: 25 },
  ],
};

/* ==========================================================================
   Histoire réelle des franchises (best-effort) : titres, années de sacre,
   légendes / numéros retirés. Sert de socle historique aux fiches de franchise.
   ========================================================================== */
const FRANCHISE_LORE = {
  BOS: { titles: 18, years: [1957,1959,1960,1961,1962,1963,1964,1965,1966,1968,1969,1974,1976,1981,1984,1986,2008,2024], legends: ['Bill Russell #6','Larry Bird #33','John Havlicek #17','Paul Pierce #34','Kevin Garnett #5'] },
  LAL: { titles: 17, years: [1949,1950,1952,1953,1954,1972,1980,1982,1985,1987,1988,2000,2001,2002,2009,2010,2020], legends: ['Magic Johnson #32','Kobe Bryant #24','Kareem Abdul-Jabbar #33','Shaquille O\'Neal #34','Jerry West #44'] },
  GSW: { titles: 7, years: [1947,1956,1975,2015,2017,2018,2022], legends: ['Stephen Curry #30','Wilt Chamberlain #13','Rick Barry #24','Klay Thompson #11'] },
  CHI: { titles: 6, years: [1991,1992,1993,1996,1997,1998], legends: ['Michael Jordan #23','Scottie Pippen #33','Dennis Rodman #91'] },
  SAS: { titles: 5, years: [1999,2003,2005,2007,2014], legends: ['Tim Duncan #21','David Robinson #50','Manu Ginóbili #20','Tony Parker #9'] },
  PHI: { titles: 3, years: [1955,1967,1983], legends: ['Julius Erving #6','Allen Iverson #3','Wilt Chamberlain #13','Charles Barkley #34'] },
  DET: { titles: 3, years: [1989,1990,2004], legends: ['Isiah Thomas #11','Joe Dumars #4','Bill Laimbeer #40','Ben Wallace #3'] },
  MIA: { titles: 3, years: [2006,2012,2013], legends: ['Dwyane Wade #3','Alonzo Mourning #33','Udonis Haslem #40'] },
  NYK: { titles: 2, years: [1970,1973], legends: ['Walt Frazier #10','Willis Reed #19','Patrick Ewing #33'] },
  HOU: { titles: 2, years: [1994,1995], legends: ['Hakeem Olajuwon #34','Yao Ming #11','Clyde Drexler #22'] },
  MIL: { titles: 2, years: [1971,2021], legends: ['Kareem Abdul-Jabbar #33','Oscar Robertson #1','Giannis Antetokounmpo #34'] },
  OKC: { titles: 1, years: [1979], legends: ['Gary Payton #20','Kevin Durant #35','Russell Westbrook #0'] },
  DEN: { titles: 1, years: [2023], legends: ['Nikola Jokić #15','Alex English #2','Dikembe Mutombo #55'] },
  DAL: { titles: 1, years: [2011], legends: ['Dirk Nowitzki #41','Rolando Blackman #22'] },
  TOR: { titles: 1, years: [2019], legends: ['Kyle Lowry #7','Vince Carter #15','DeMar DeRozan #10'] },
  CLE: { titles: 1, years: [2016], legends: ['LeBron James #23','Austin Carr #34','Žydrūnas Ilgauskas #11'] },
  WAS: { titles: 1, years: [1978], legends: ['Wes Unseld #41','Elvin Hayes #11','Gilbert Arenas #0'] },
  POR: { titles: 1, years: [1977], legends: ['Bill Walton #32','Clyde Drexler #22','Damian Lillard #0'] },
  SAC: { titles: 1, years: [1951], legends: ['Oscar Robertson #14','Chris Webber #4','Mitch Richmond #2'] },
  ATL: { titles: 1, years: [1958], legends: ['Bob Pettit #9','Dominique Wilkins #21','Lou Hudson #23'] },
  BKN: { titles: 0, years: [], legends: ['Jason Kidd #5','Vince Carter #15','Dražen Petrović #3'] },
  IND: { titles: 0, years: [], legends: ['Reggie Miller #31','Mel Daniels #34','George McGinnis #30'] },
  MIN: { titles: 0, years: [], legends: ['Kevin Garnett #21','Kevin Love','Anthony Edwards'] },
  UTA: { titles: 0, years: [], legends: ['John Stockton #12','Karl Malone #32','Pete Maravich #7'] },
  ORL: { titles: 0, years: [], legends: ['Shaquille O\'Neal','Dwight Howard #12','Nick Anderson #25'] },
  CHA: { titles: 0, years: [], legends: ['Muggsy Bogues #1','Larry Johnson #2','Kemba Walker #15'] },
  PHX: { titles: 0, years: [], legends: ['Steve Nash #13','Charles Barkley #34','Walter Davis #6'] },
  LAC: { titles: 0, years: [], legends: ['Chris Paul #3','Blake Griffin #32','Bob McAdoo #11'] },
  MEM: { titles: 0, years: [], legends: ['Marc Gasol #33','Zach Randolph #50','Mike Conley #11'] },
  NOP: { titles: 0, years: [], legends: ['Chris Paul #3','Anthony Davis','David West #30'] },
};

/* ==========================================================================
   Prospects de draft — têtes d'affiche réelles connues (le reste est projeté)
   La classe 2026 est déjà en NBA (Dybantsa, Boozer, Peterson…). La cuvée 2027
   manque de superstar établie ; seul le n°1 pressenti est connu à ce jour.
   ⚠️ Prospects futurs = projections incertaines (lycéens/universitaires).
   ========================================================================== */
const REAL_PROSPECTS = {
  2027: [
    { n: 'Tyran Stokes', pos: 'SF', ovr: 76, pot: 92 }, // n°1 pressenti (source : ESPN/SI)
  ],
  // 2028+ : prospects projetés (générés), aucune donnée réelle fiable à ce stade.
};

/* ==========================================================================
   Agents libres vétérans (best-effort). Disponibilité fictionnalisée pour le jeu.
   ========================================================================== */
const REAL_FREE_AGENTS = [
  { n: 'Chris Paul', pos: 'PG', ovr: 77, age: 40 },
  { n: 'Russell Westbrook', pos: 'PG', ovr: 76, age: 37 },
  { n: 'Ben Simmons', pos: 'PG', ovr: 74, age: 29 },
  { n: 'Kelly Olynyk', pos: 'C', ovr: 76, age: 34 },
  { n: 'Lonnie Walker IV', pos: 'SG', ovr: 74, age: 27 },
  { n: 'Seth Curry', pos: 'SG', ovr: 74, age: 35 },
  { n: 'Markieff Morris', pos: 'PF', ovr: 71, age: 36 },
  { n: 'Robin Lopez', pos: 'C', ovr: 71, age: 37 },
  { n: 'JaVale McGee', pos: 'C', ovr: 71, age: 38 },
  { n: 'Nerlens Noel', pos: 'C', ovr: 71, age: 31 },
  { n: 'Otto Porter Jr.', pos: 'SF', ovr: 72, age: 32 },
  { n: 'Joe Ingles', pos: 'SF', ovr: 73, age: 38 },
  { n: 'Reggie Jackson', pos: 'PG', ovr: 73, age: 35 },
  { n: 'Delon Wright', pos: 'PG', ovr: 73, age: 33 },
  { n: 'Wesley Matthews', pos: 'SG', ovr: 71, age: 39 },
  { n: 'Bismack Biyombo', pos: 'C', ovr: 71, age: 33 },
  { n: 'Justin Holiday', pos: 'SF', ovr: 71, age: 36 },
  { n: 'Patty Mills', pos: 'PG', ovr: 71, age: 37 },
  { n: 'Alex Len', pos: 'C', ovr: 71, age: 32 },
  { n: 'Cory Joseph', pos: 'PG', ovr: 71, age: 34 },
  { n: 'Taj Gibson', pos: 'PF', ovr: 70, age: 40 },
  { n: 'Kevin Knox II', pos: 'SF', ovr: 72, age: 26 },
  { n: 'Davis Bertans', pos: 'PF', ovr: 72, age: 33 },
];

/* ==========================================================================
   Agents libres vétérans par époque (best-effort) : noms réels de joueurs
   emblématiques de chaque ère, pour que le marché des transferts « colle à la
   réalité » plutôt que de proposer des noms générés. Disponibilité fictionnalisée.
   ========================================================================== */
const ERA_FREE_AGENTS = {
  e1968: [
    { n: 'Hal Greer', pos: 'SG' }, { n: 'Sam Jones', pos: 'SG' }, { n: 'Dave Bing', pos: 'PG' },
    { n: 'Gail Goodrich', pos: 'PG' }, { n: 'Bob Boozer', pos: 'PF' }, { n: 'Chet Walker', pos: 'SF' },
    { n: 'Zelmo Beaty', pos: 'C' }, { n: 'Guy Rodgers', pos: 'PG' }, { n: 'Tom Van Arsdale', pos: 'SG' },
    { n: 'Dick Van Arsdale', pos: 'SF' }, { n: 'Archie Clark', pos: 'PG' }, { n: 'Happy Hairston', pos: 'PF' },
    { n: 'Don Ohl', pos: 'SG' }, { n: 'Len Wilkens', pos: 'PG' }, { n: 'Rudy LaRusso', pos: 'PF' },
    { n: 'Walt Bellamy', pos: 'C' },
  ],
  e1986: [
    { n: 'Alex English', pos: 'SF' }, { n: 'Marques Johnson', pos: 'SF' }, { n: 'Bernard King', pos: 'SF' },
    { n: 'Andrew Toney', pos: 'SG' }, { n: 'World B. Free', pos: 'SG' }, { n: 'Reggie Theus', pos: 'SG' },
    { n: 'Norm Nixon', pos: 'PG' }, { n: 'Gus Williams', pos: 'PG' }, { n: 'Jack Sikma', pos: 'C' },
    { n: 'Bill Laimbeer', pos: 'C' }, { n: 'Buck Williams', pos: 'PF' }, { n: 'Roy Tarpley', pos: 'PF' },
    { n: 'Eddie Johnson', pos: 'SF' }, { n: 'Michael Cooper', pos: 'SG' }, { n: 'Jeff Malone', pos: 'SG' },
    { n: 'Otis Thorpe', pos: 'PF' },
  ],
  e1996: [
    { n: 'Mitch Richmond', pos: 'SG' }, { n: 'Reggie Miller', pos: 'SG' }, { n: 'Dan Majerle', pos: 'SG' },
    { n: 'Kevin Johnson', pos: 'PG' }, { n: 'Mark Price', pos: 'PG' }, { n: 'Detlef Schrempf', pos: 'SF' },
    { n: 'Horace Grant', pos: 'PF' }, { n: 'Dikembe Mutombo', pos: 'C' }, { n: 'Vin Baker', pos: 'PF' },
    { n: 'Cedric Ceballos', pos: 'SF' }, { n: 'Jim Jackson', pos: 'SG' }, { n: 'Rod Strickland', pos: 'PG' },
    { n: 'Nick Van Exel', pos: 'PG' }, { n: 'Christian Laettner', pos: 'PF' }, { n: 'Dale Davis', pos: 'PF' },
    { n: 'Tom Gugliotta', pos: 'PF' },
  ],
  e2016: [
    { n: 'Dwyane Wade', pos: 'SG' }, { n: 'Carmelo Anthony', pos: 'SF' }, { n: 'Pau Gasol', pos: 'C' },
    { n: 'Al Horford', pos: 'C' }, { n: 'Andre Iguodala', pos: 'SF' }, { n: 'Rajon Rondo', pos: 'PG' },
    { n: 'Jeff Teague', pos: 'PG' }, { n: 'Nicolas Batum', pos: 'SF' }, { n: 'Ryan Anderson', pos: 'PF' },
    { n: 'Bismack Biyombo', pos: 'C' }, { n: 'Evan Turner', pos: 'SG' }, { n: 'Marvin Williams', pos: 'PF' },
    { n: 'Jared Dudley', pos: 'SF' }, { n: 'Ian Mahinmi', pos: 'C' }, { n: 'Courtney Lee', pos: 'SG' },
    { n: 'Solomon Hill', pos: 'SF' },
  ],
  euro: [
    { n: 'Sergio Llull', pos: 'PG' }, { n: 'Vasilije Micić', pos: 'PG' }, { n: 'Nando de Colo', pos: 'SG' },
    { n: 'Kostas Sloukas', pos: 'PG' }, { n: 'Mike James', pos: 'PG' }, { n: 'Shane Larkin', pos: 'PG' },
    { n: 'Nick Calathes', pos: 'PG' }, { n: 'Will Clyburn', pos: 'SF' }, { n: 'Ekpe Udoh', pos: 'C' },
    { n: 'Jan Veselý', pos: 'C' }, { n: 'Georgios Printezis', pos: 'PF' }, { n: 'Edy Tavares', pos: 'C' },
    { n: 'Marius Grigonis', pos: 'SG' }, { n: 'Cory Higgins', pos: 'SG' }, { n: 'Tornike Shengelia', pos: 'PF' },
    { n: 'Nikola Milutinov', pos: 'C' },
  ],
};
