/* ==========================================================================
   NBA My Era — Effectifs (best-effort au 10/08/2026)
   --------------------------------------------------------------------------
   n = nom, pos = poste, ovr = note, age = âge (approx.), pot = potentiel (opt.)

   ⚠️  IMPORTANT — À VÉRIFIER
   Instantané reconstitué au 10/08/2026 à partir de recherches web (sources :
   NBA.com, ESPN, Yahoo Sports, Bleacher Report, SI, HoopsHype…). Les mouvements
   de l'intersaison 2026 (free agency, draft 2026, transferts) évoluent vite et
   certaines infos proviennent d'extraits non officiels : des erreurs sont
   possibles, surtout sur les joueurs de rotation. Tout est modifiable en jeu
   (transferts, coupes, agents libres, draft). Le fond de banc est complété
   automatiquement par des joueurs générés.

   Principaux mouvements intégrés : Luka Dončić→LAL / Anthony Davis→DAL,
   Cooper Flagg (n°1 2025)→DAL, Kevin Durant→HOU, Jalen Green & Dillon Brooks→PHX,
   LeBron James & Jaylen Brown→PHI / Paul George→BOS, Giannis & Bobby Portis→MIA /
   Tyler Herro, Kel'el Ware, Jaime Jaquez→MIL, Myles Turner→MIL, Ja Morant→POR,
   LaMelo Ball→MIN / Julius Randle→BKN, Michael Porter Jr→BKN / Cam Johnson→DEN,
   Jimmy Butler & Andrew Wiggins→(Butler)GSW/(Wiggins)MIA, De'Aaron Fox→SAS,
   Zach LaVine→SAC, Darius Garland→LAC, Desmond Bane→ORL, Brandon Ingram→TOR,
   Nic Claxton & Norman Powell→CHI, Lu Dort→ATL, Kristaps Porzingis→ATL,
   AJ Dybantsa (n°1 2026)→WAS, Deandre Ayton→WAS, Walker Kessler→LAL.
   ========================================================================== */

const REAL_ROSTERS = {
  /* ------------------------------- EST ---------------------------------- */
  BOS: [
    { n: 'Jayson Tatum', pos: 'SF', ovr: 93, age: 27 },
    { n: 'Paul George', pos: 'SG', ovr: 84, age: 35 },
    { n: 'Derrick White', pos: 'PG', ovr: 85, age: 31 },
    { n: 'Anfernee Simons', pos: 'SG', ovr: 81, age: 27 },
    { n: 'Payton Pritchard', pos: 'PG', ovr: 81, age: 28 },
    { n: 'Neemias Queta', pos: 'C', ovr: 77, age: 26 },
    { n: 'Sam Hauser', pos: 'SF', ovr: 76, age: 28 },
    { n: 'Baylor Scheierman', pos: 'SG', ovr: 73, age: 25 },
  ],
  BKN: [
    { n: 'Michael Porter Jr.', pos: 'SF', ovr: 82, age: 27 },
    { n: 'Julius Randle', pos: 'PF', ovr: 83, age: 31 },
    { n: 'Cam Thomas', pos: 'SG', ovr: 81, age: 24 },
    { n: 'Terance Mann', pos: 'SG', ovr: 75, age: 29 },
    { n: 'Egor Demin', pos: 'PG', ovr: 74, age: 20, pot: 85 },
    { n: "Day'Ron Sharpe", pos: 'C', ovr: 74, age: 24 },
    { n: 'Noah Clowney', pos: 'PF', ovr: 74, age: 21, pot: 83 },
    { n: 'Ziaire Williams', pos: 'SF', ovr: 74, age: 24 },
  ],
  NYK: [
    { n: 'Jalen Brunson', pos: 'PG', ovr: 91, age: 29 },
    { n: 'Karl-Anthony Towns', pos: 'C', ovr: 88, age: 30 },
    { n: 'Mikal Bridges', pos: 'SF', ovr: 85, age: 29 },
    { n: 'OG Anunoby', pos: 'SF', ovr: 84, age: 28 },
    { n: 'Josh Hart', pos: 'SG', ovr: 82, age: 30 },
    { n: 'Mitchell Robinson', pos: 'C', ovr: 79, age: 27 },
    { n: 'Miles McBride', pos: 'PG', ovr: 76, age: 25 },
    { n: 'Guerschon Yabusele', pos: 'PF', ovr: 76, age: 30 },
  ],
  PHI: [
    { n: 'Joel Embiid', pos: 'C', ovr: 93, age: 32 },
    { n: 'Tyrese Maxey', pos: 'PG', ovr: 90, age: 25 },
    { n: 'Jaylen Brown', pos: 'SG', ovr: 89, age: 29 },
    { n: 'LeBron James', pos: 'PF', ovr: 88, age: 41 },
    { n: 'VJ Edgecombe', pos: 'SG', ovr: 78, age: 20, pot: 89 },
    { n: 'Kelly Oubre Jr.', pos: 'SF', ovr: 79, age: 30 },
    { n: 'Jared McCain', pos: 'PG', ovr: 78, age: 22, pot: 86 },
    { n: 'Andre Drummond', pos: 'C', ovr: 75, age: 32 },
    { n: 'Adem Bona', pos: 'C', ovr: 73, age: 22, pot: 82 },
  ],
  TOR: [
    { n: 'Scottie Barnes', pos: 'PF', ovr: 86, age: 24, pot: 92 },
    { n: 'Brandon Ingram', pos: 'SF', ovr: 84, age: 29 },
    { n: 'RJ Barrett', pos: 'SG', ovr: 83, age: 25 },
    { n: 'Immanuel Quickley', pos: 'PG', ovr: 81, age: 26 },
    { n: 'Jakob Poeltl', pos: 'C', ovr: 80, age: 30 },
    { n: 'Gradey Dick', pos: 'SG', ovr: 77, age: 22, pot: 84 },
    { n: "Ja'Kobe Walter", pos: 'SG', ovr: 74, age: 21, pot: 83 },
    { n: 'Ochai Agbaji', pos: 'SG', ovr: 74, age: 25 },
  ],
  CHI: [
    { n: 'Josh Giddey', pos: 'PG', ovr: 82, age: 23 },
    { n: 'Coby White', pos: 'SG', ovr: 82, age: 26 },
    { n: 'Nic Claxton', pos: 'C', ovr: 81, age: 26 },
    { n: 'Norman Powell', pos: 'SG', ovr: 81, age: 33 },
    { n: 'Matas Buzelis', pos: 'PF', ovr: 79, age: 21, pot: 88 },
    { n: 'Ayo Dosunmu', pos: 'SG', ovr: 77, age: 26 },
    { n: 'Kevin Huerter', pos: 'SF', ovr: 75, age: 27 },
    { n: 'Patrick Williams', pos: 'PF', ovr: 75, age: 24 },
    { n: 'Noa Essengue', pos: 'PF', ovr: 72, age: 19, pot: 84 },
  ],
  CLE: [
    { n: 'Donovan Mitchell', pos: 'SG', ovr: 92, age: 29 },
    { n: 'Evan Mobley', pos: 'PF', ovr: 89, age: 24, pot: 94 },
    { n: 'Jarrett Allen', pos: 'C', ovr: 84, age: 28 },
    { n: "De'Andre Hunter", pos: 'SF', ovr: 79, age: 28 },
    { n: 'Max Strus', pos: 'SF', ovr: 78, age: 30 },
    { n: 'Ty Jerome', pos: 'PG', ovr: 78, age: 28 },
    { n: 'Sam Merrill', pos: 'SG', ovr: 75, age: 30 },
    { n: 'Craig Porter Jr.', pos: 'PG', ovr: 73, age: 25 },
  ],
  DET: [
    { n: 'Cade Cunningham', pos: 'PG', ovr: 90, age: 24, pot: 94 },
    { n: 'Jalen Duren', pos: 'C', ovr: 82, age: 22, pot: 87 },
    { n: 'Ausar Thompson', pos: 'SF', ovr: 80, age: 23, pot: 88 },
    { n: 'Jaden Ivey', pos: 'SG', ovr: 80, age: 23 },
    { n: 'Tobias Harris', pos: 'SF', ovr: 78, age: 33 },
    { n: 'Isaiah Stewart', pos: 'C', ovr: 77, age: 24 },
    { n: 'Duncan Robinson', pos: 'SF', ovr: 77, age: 32 },
    { n: 'Marcus Sasser', pos: 'PG', ovr: 74, age: 25 },
  ],
  IND: [
    { n: 'Tyrese Haliburton', pos: 'PG', ovr: 89, age: 25 },
    { n: 'Pascal Siakam', pos: 'PF', ovr: 87, age: 31 },
    { n: 'Bennedict Mathurin', pos: 'SG', ovr: 81, age: 23, pot: 87 },
    { n: 'Andrew Nembhard', pos: 'PG', ovr: 78, age: 25 },
    { n: 'Aaron Nesmith', pos: 'SF', ovr: 78, age: 26 },
    { n: 'Obi Toppin', pos: 'PF', ovr: 77, age: 27 },
    { n: 'T.J. McConnell', pos: 'PG', ovr: 76, age: 33 },
    { n: 'Isaiah Jackson', pos: 'C', ovr: 76, age: 24 },
    { n: 'Jarace Walker', pos: 'PF', ovr: 75, age: 22, pot: 84 },
  ],
  MIL: [
    { n: 'Tyler Herro', pos: 'SG', ovr: 85, age: 26 },
    { n: 'Myles Turner', pos: 'C', ovr: 82, age: 29 },
    { n: 'Kyle Kuzma', pos: 'PF', ovr: 80, age: 30 },
    { n: "Kel'el Ware", pos: 'C', ovr: 79, age: 22, pot: 88 },
    { n: 'Jaime Jaquez Jr.', pos: 'SF', ovr: 78, age: 25 },
    { n: 'Gary Trent Jr.', pos: 'SG', ovr: 77, age: 27 },
    { n: 'Kasparas Jakucionis', pos: 'PG', ovr: 74, age: 20, pot: 84 },
    { n: 'AJ Green', pos: 'SG', ovr: 74, age: 26 },
    { n: 'Ryan Rollins', pos: 'PG', ovr: 73, age: 23 },
  ],
  ATL: [
    { n: 'Trae Young', pos: 'PG', ovr: 88, age: 27 },
    { n: 'Jalen Johnson', pos: 'PF', ovr: 84, age: 24, pot: 89 },
    { n: 'Kristaps Porzingis', pos: 'C', ovr: 83, age: 30 },
    { n: 'Dyson Daniels', pos: 'SG', ovr: 81, age: 23, pot: 86 },
    { n: 'Lu Dort', pos: 'SG', ovr: 79, age: 26 },
    { n: 'Onyeka Okongwu', pos: 'C', ovr: 80, age: 25 },
    { n: 'Zaccharie Risacher', pos: 'SF', ovr: 78, age: 20, pot: 88 },
    { n: 'Nickeil Alexander-Walker', pos: 'SG', ovr: 77, age: 27 },
  ],
  CHA: [
    { n: 'Brandon Miller', pos: 'SF', ovr: 82, age: 23, pot: 89 },
    { n: 'Collin Sexton', pos: 'PG', ovr: 79, age: 27 },
    { n: 'Kon Knueppel', pos: 'SG', ovr: 77, age: 20, pot: 86 },
    { n: 'Grant Williams', pos: 'PF', ovr: 76, age: 27 },
    { n: 'Tre Mann', pos: 'PG', ovr: 76, age: 24 },
    { n: 'Josh Green', pos: 'SG', ovr: 75, age: 25 },
    { n: 'Moussa Diabaté', pos: 'C', ovr: 74, age: 24 },
    { n: 'Tidjane Salaun', pos: 'PF', ovr: 74, age: 20, pot: 84 },
    { n: 'Ryan Kalkbrenner', pos: 'C', ovr: 72, age: 23, pot: 81 },
  ],
  MIA: [
    { n: 'Giannis Antetokounmpo', pos: 'PF', ovr: 96, age: 31 },
    { n: 'Bam Adebayo', pos: 'C', ovr: 88, age: 28 },
    { n: 'Andrew Wiggins', pos: 'SF', ovr: 81, age: 30 },
    { n: 'Bobby Portis', pos: 'PF', ovr: 80, age: 30 },
    { n: 'Davion Mitchell', pos: 'PG', ovr: 78, age: 27 },
    { n: 'Nikola Jovic', pos: 'SF', ovr: 77, age: 22, pot: 85 },
    { n: 'Tim Hardaway Jr.', pos: 'SG', ovr: 76, age: 33 },
    { n: 'Pelle Larsson', pos: 'SG', ovr: 73, age: 24 },
  ],
  ORL: [
    { n: 'Paolo Banchero', pos: 'PF', ovr: 88, age: 22, pot: 93 },
    { n: 'Franz Wagner', pos: 'SF', ovr: 86, age: 24, pot: 90 },
    { n: 'Desmond Bane', pos: 'SG', ovr: 84, age: 27 },
    { n: 'Jalen Suggs', pos: 'PG', ovr: 81, age: 24 },
    { n: 'Wendell Carter Jr.', pos: 'C', ovr: 79, age: 26 },
    { n: 'Jonathan Isaac', pos: 'PF', ovr: 78, age: 28 },
    { n: 'Anthony Black', pos: 'SG', ovr: 75, age: 21, pot: 84 },
    { n: 'Tristan da Silva', pos: 'SF', ovr: 75, age: 24 },
  ],
  WAS: [
    { n: 'AJ Dybantsa', pos: 'SF', ovr: 78, age: 19, pot: 93 },
    { n: 'CJ McCollum', pos: 'SG', ovr: 79, age: 34 },
    { n: 'Khris Middleton', pos: 'SF', ovr: 78, age: 34 },
    { n: 'Deandre Ayton', pos: 'C', ovr: 80, age: 27 },
    { n: 'Alex Sarr', pos: 'C', ovr: 78, age: 20, pot: 88 },
    { n: 'Bilal Coulibaly', pos: 'SF', ovr: 78, age: 21, pot: 87 },
    { n: 'Bub Carrington', pos: 'PG', ovr: 76, age: 20, pot: 84 },
    { n: 'Tre Johnson', pos: 'SG', ovr: 75, age: 19, pot: 86 },
    { n: 'Kyshawn George', pos: 'SF', ovr: 74, age: 21, pot: 83 },
  ],
  /* ------------------------------ OUEST --------------------------------- */
  DEN: [
    { n: 'Nikola Jokic', pos: 'C', ovr: 98, age: 30 },
    { n: 'Jamal Murray', pos: 'PG', ovr: 86, age: 28 },
    { n: 'Aaron Gordon', pos: 'PF', ovr: 84, age: 30 },
    { n: 'Cam Johnson', pos: 'SF', ovr: 82, age: 30 },
    { n: 'Christian Braun', pos: 'SG', ovr: 79, age: 24 },
    { n: 'Jonas Valanciunas', pos: 'C', ovr: 78, age: 34 },
    { n: 'Peyton Watson', pos: 'SF', ovr: 77, age: 23, pot: 84 },
    { n: 'Julian Strawther', pos: 'SG', ovr: 74, age: 23 },
  ],
  MIN: [
    { n: 'Anthony Edwards', pos: 'SG', ovr: 93, age: 24, pot: 96 },
    { n: 'LaMelo Ball', pos: 'PG', ovr: 86, age: 24, pot: 91 },
    { n: 'Rudy Gobert', pos: 'C', ovr: 85, age: 33 },
    { n: 'Jaden McDaniels', pos: 'SF', ovr: 82, age: 25 },
    { n: 'Naz Reid', pos: 'C', ovr: 81, age: 26 },
    { n: 'Donte DiVincenzo', pos: 'SG', ovr: 80, age: 29 },
    { n: 'Mike Conley', pos: 'PG', ovr: 76, age: 38 },
    { n: 'Terrence Shannon Jr.', pos: 'SG', ovr: 76, age: 25 },
    { n: 'Rob Dillingham', pos: 'PG', ovr: 75, age: 21, pot: 85 },
  ],
  OKC: [
    { n: 'Shai Gilgeous-Alexander', pos: 'SG', ovr: 98, age: 27 },
    { n: 'Chet Holmgren', pos: 'C', ovr: 88, age: 23, pot: 93 },
    { n: 'Jalen Williams', pos: 'SF', ovr: 87, age: 24, pot: 91 },
    { n: 'Isaiah Hartenstein', pos: 'C', ovr: 80, age: 27 },
    { n: 'Alex Caruso', pos: 'SG', ovr: 79, age: 32 },
    { n: 'Cason Wallace', pos: 'PG', ovr: 77, age: 22, pot: 85 },
    { n: 'Aaron Wiggins', pos: 'SG', ovr: 76, age: 27 },
    { n: 'Isaiah Joe', pos: 'SG', ovr: 75, age: 26 },
  ],
  POR: [
    { n: 'Ja Morant', pos: 'PG', ovr: 88, age: 26, pot: 91 },
    { n: 'Deni Avdija', pos: 'SF', ovr: 82, age: 25 },
    { n: 'Jrue Holiday', pos: 'PG', ovr: 82, age: 35 },
    { n: 'Shaedon Sharpe', pos: 'SG', ovr: 79, age: 22, pot: 87 },
    { n: 'Toumani Camara', pos: 'SF', ovr: 77, age: 25 },
    { n: 'Donovan Clingan', pos: 'C', ovr: 77, age: 22, pot: 86 },
    { n: 'Scoot Henderson', pos: 'PG', ovr: 76, age: 22, pot: 85 },
    { n: 'Robert Williams III', pos: 'C', ovr: 76, age: 28 },
  ],
  UTA: [
    { n: 'Lauri Markkanen', pos: 'PF', ovr: 85, age: 28 },
    { n: 'John Collins', pos: 'PF', ovr: 80, age: 28 },
    { n: 'Keyonte George', pos: 'PG', ovr: 78, age: 22, pot: 86 },
    { n: 'Ace Bailey', pos: 'SF', ovr: 77, age: 19, pot: 89 },
    { n: 'Kyle Filipowski', pos: 'C', ovr: 76, age: 22, pot: 84 },
    { n: 'Isaiah Collier', pos: 'PG', ovr: 75, age: 21, pot: 84 },
    { n: 'Taylor Hendricks', pos: 'PF', ovr: 75, age: 22, pot: 84 },
    { n: 'Walter Clayton Jr.', pos: 'PG', ovr: 73, age: 23, pot: 82 },
  ],
  GSW: [
    { n: 'Stephen Curry', pos: 'PG', ovr: 93, age: 37 },
    { n: 'Jimmy Butler', pos: 'SF', ovr: 87, age: 36 },
    { n: 'Draymond Green', pos: 'PF', ovr: 81, age: 35 },
    { n: 'Jonathan Kuminga', pos: 'PF', ovr: 80, age: 22, pot: 88 },
    { n: 'Brandin Podziemski', pos: 'SG', ovr: 79, age: 22, pot: 85 },
    { n: 'Buddy Hield', pos: 'SG', ovr: 78, age: 32 },
    { n: 'Moses Moody', pos: 'SG', ovr: 77, age: 23 },
    { n: 'Quinten Post', pos: 'C', ovr: 74, age: 25 },
  ],
  LAC: [
    { n: 'Kawhi Leonard', pos: 'SF', ovr: 89, age: 34 },
    { n: 'James Harden', pos: 'PG', ovr: 85, age: 36 },
    { n: 'Darius Garland', pos: 'PG', ovr: 84, age: 26 },
    { n: 'Ivica Zubac', pos: 'C', ovr: 83, age: 28 },
    { n: 'Brook Lopez', pos: 'C', ovr: 78, age: 37 },
    { n: 'Bogdan Bogdanovic', pos: 'SG', ovr: 77, age: 33 },
    { n: 'Derrick Jones Jr.', pos: 'SF', ovr: 75, age: 28 },
    { n: 'Kris Dunn', pos: 'PG', ovr: 75, age: 31 },
  ],
  LAL: [
    { n: 'Luka Doncic', pos: 'PG', ovr: 95, age: 26 },
    { n: 'Austin Reaves', pos: 'SG', ovr: 84, age: 27 },
    { n: 'Walker Kessler', pos: 'C', ovr: 80, age: 24 },
    { n: 'Rui Hachimura', pos: 'PF', ovr: 79, age: 28 },
    { n: 'Quentin Grimes', pos: 'SF', ovr: 78, age: 25 },
    { n: 'Dalton Knecht', pos: 'SG', ovr: 76, age: 24, pot: 83 },
    { n: 'Sandro Mamukelashvili', pos: 'PF', ovr: 75, age: 26 },
    { n: 'Jarred Vanderbilt', pos: 'PF', ovr: 75, age: 26 },
    { n: 'Jake LaRavia', pos: 'SF', ovr: 74, age: 24 },
  ],
  PHX: [
    { n: 'Devin Booker', pos: 'SG', ovr: 91, age: 29 },
    { n: 'Jalen Green', pos: 'SG', ovr: 82, age: 24, pot: 89 },
    { n: 'Dillon Brooks', pos: 'SF', ovr: 78, age: 30 },
    { n: 'Mark Williams', pos: 'C', ovr: 79, age: 24, pot: 85 },
    { n: 'Grayson Allen', pos: 'SG', ovr: 78, age: 30 },
    { n: 'Nick Richards', pos: 'C', ovr: 75, age: 28 },
    { n: 'Ryan Dunn', pos: 'SF', ovr: 75, age: 22, pot: 84 },
    { n: 'Khaman Maluach', pos: 'C', ovr: 74, age: 19, pot: 87 },
    { n: 'Collin Gillespie', pos: 'PG', ovr: 74, age: 26 },
  ],
  SAC: [
    { n: 'Domantas Sabonis', pos: 'C', ovr: 87, age: 29 },
    { n: 'Zach LaVine', pos: 'SG', ovr: 83, age: 31 },
    { n: 'DeMar DeRozan', pos: 'SF', ovr: 82, age: 36 },
    { n: 'Keegan Murray', pos: 'SF', ovr: 81, age: 25 },
    { n: 'Malik Monk', pos: 'SG', ovr: 79, age: 27 },
    { n: 'Devin Carter', pos: 'SG', ovr: 74, age: 23, pot: 83 },
    { n: 'Keon Ellis', pos: 'SG', ovr: 75, age: 25 },
    { n: 'Trey Lyles', pos: 'PF', ovr: 73, age: 30 },
  ],
  DAL: [
    { n: 'Anthony Davis', pos: 'C', ovr: 93, age: 32 },
    { n: 'Cooper Flagg', pos: 'SF', ovr: 82, age: 19, pot: 96 },
    { n: 'Kyrie Irving', pos: 'PG', ovr: 88, age: 33 },
    { n: 'Klay Thompson', pos: 'SG', ovr: 80, age: 36 },
    { n: "D'Angelo Russell", pos: 'PG', ovr: 78, age: 30 },
    { n: 'Daniel Gafford', pos: 'C', ovr: 80, age: 27 },
    { n: 'Dereck Lively II', pos: 'C', ovr: 79, age: 22, pot: 87 },
    { n: 'P.J. Washington', pos: 'PF', ovr: 79, age: 27 },
    { n: 'Max Christie', pos: 'SG', ovr: 76, age: 23 },
  ],
  HOU: [
    { n: 'Kevin Durant', pos: 'SF', ovr: 93, age: 37 },
    { n: 'Alperen Sengun', pos: 'C', ovr: 86, age: 23, pot: 91 },
    { n: 'Amen Thompson', pos: 'SF', ovr: 82, age: 23, pot: 91 },
    { n: 'Fred VanVleet', pos: 'PG', ovr: 80, age: 32 },
    { n: 'Jabari Smith Jr.', pos: 'PF', ovr: 80, age: 22, pot: 88 },
    { n: 'Reed Sheppard', pos: 'PG', ovr: 78, age: 21, pot: 86 },
    { n: 'Tari Eason', pos: 'SF', ovr: 78, age: 24, pot: 85 },
    { n: 'Steven Adams', pos: 'C', ovr: 76, age: 32 },
    { n: 'Dorian Finney-Smith', pos: 'SF', ovr: 76, age: 33 },
  ],
  MEM: [
    { n: 'Jaren Jackson Jr.', pos: 'PF', ovr: 86, age: 26 },
    { n: 'Zach Edey', pos: 'C', ovr: 78, age: 23, pot: 85 },
    { n: 'Santi Aldama', pos: 'PF', ovr: 77, age: 25 },
    { n: 'Jaylen Wells', pos: 'SF', ovr: 76, age: 22, pot: 84 },
    { n: 'Scotty Pippen Jr.', pos: 'PG', ovr: 75, age: 25 },
    { n: 'GG Jackson', pos: 'SF', ovr: 75, age: 21, pot: 85 },
    { n: 'Cedric Coward', pos: 'SG', ovr: 74, age: 22, pot: 84 },
    { n: 'Vince Williams Jr.', pos: 'SG', ovr: 74, age: 25 },
  ],
  NOP: [
    { n: 'Zion Williamson', pos: 'PF', ovr: 87, age: 25, pot: 91 },
    { n: 'Trey Murphy III', pos: 'SF', ovr: 82, age: 25 },
    { n: 'Dejounte Murray', pos: 'PG', ovr: 82, age: 28 },
    { n: 'Jordan Poole', pos: 'SG', ovr: 80, age: 26 },
    { n: 'Herbert Jones', pos: 'SF', ovr: 79, age: 26 },
    { n: 'Jose Alvarado', pos: 'PG', ovr: 75, age: 27 },
    { n: 'Yves Missi', pos: 'C', ovr: 75, age: 20, pot: 84 },
    { n: 'Jeremiah Fears', pos: 'PG', ovr: 74, age: 19, pot: 85 },
    { n: 'Derik Queen', pos: 'C', ovr: 74, age: 20, pot: 85 },
  ],
  SAS: [
    { n: 'Victor Wembanyama', pos: 'C', ovr: 95, age: 21, pot: 99 },
    { n: "De'Aaron Fox", pos: 'PG', ovr: 88, age: 27 },
    { n: 'Devin Vassell', pos: 'SG', ovr: 81, age: 24 },
    { n: 'Stephon Castle', pos: 'SG', ovr: 80, age: 20, pot: 89 },
    { n: 'Dylan Harper', pos: 'SG', ovr: 78, age: 19, pot: 90 },
    { n: 'Jeremy Sochan', pos: 'PF', ovr: 78, age: 22, pot: 86 },
    { n: 'Keldon Johnson', pos: 'SF', ovr: 77, age: 25 },
    { n: 'Harrison Barnes', pos: 'SF', ovr: 76, age: 33 },
    { n: 'Luke Kornet', pos: 'C', ovr: 74, age: 30 },
  ],
};

/* ==========================================================================
   Prospects de draft — têtes d'affiche réelles connues (le reste est projeté)
   La classe 2026 est déjà en NBA (Dybantsa, Boozer, Peterson…). La cuvée 2027
   manque de superstar établie ; seul le n°1 pressenti est connu à ce jour.
   ⚠️ Prospects futurs = projections incertaines (lycéens/universitaires).
   ========================================================================== */
const REAL_PROSPECTS = {
  2027: [
    { n: 'Tyran Stokes', pos: 'SF', ovr: 76, pot: 92 }, // n°1 pressenti (source : ESPN/SI)
  ],
  // 2028+ : prospects projetés (générés), aucune donnée réelle fiable à ce stade.
};

/* ==========================================================================
   Agents libres vétérans (best-effort). Disponibilité fictionnalisée pour le jeu.
   ========================================================================== */
const REAL_FREE_AGENTS = [
  { n: 'Chris Paul', pos: 'PG', ovr: 77, age: 40 },
  { n: 'Russell Westbrook', pos: 'PG', ovr: 76, age: 37 },
  { n: 'Ben Simmons', pos: 'PG', ovr: 74, age: 29 },
  { n: 'Kelly Olynyk', pos: 'C', ovr: 76, age: 34 },
  { n: 'Gary Payton II', pos: 'SG', ovr: 74, age: 33 },
  { n: 'Lonnie Walker IV', pos: 'SG', ovr: 74, age: 27 },
  { n: 'Seth Curry', pos: 'SG', ovr: 74, age: 35 },
  { n: 'Markieff Morris', pos: 'PF', ovr: 71, age: 36 },
  { n: 'Robin Lopez', pos: 'C', ovr: 71, age: 37 },
  { n: 'JaVale McGee', pos: 'C', ovr: 71, age: 38 },
  { n: 'Nerlens Noel', pos: 'C', ovr: 71, age: 31 },
  { n: 'Otto Porter Jr.', pos: 'SF', ovr: 72, age: 32 },
  { n: 'Joe Ingles', pos: 'SF', ovr: 73, age: 38 },
  { n: 'Reggie Jackson', pos: 'PG', ovr: 73, age: 35 },
  { n: 'Delon Wright', pos: 'PG', ovr: 73, age: 33 },
  { n: 'Wesley Matthews', pos: 'SG', ovr: 71, age: 39 },
  { n: 'Bismack Biyombo', pos: 'C', ovr: 71, age: 33 },
  { n: 'Justin Holiday', pos: 'SF', ovr: 71, age: 36 },
  { n: 'Patty Mills', pos: 'PG', ovr: 71, age: 37 },
  { n: 'Alex Len', pos: 'C', ovr: 71, age: 32 },
  { n: 'Cory Joseph', pos: 'PG', ovr: 71, age: 34 },
  { n: 'Taj Gibson', pos: 'PF', ovr: 70, age: 40 },
  { n: 'Kevin Knox II', pos: 'SF', ovr: 72, age: 26 },
  { n: 'Davis Bertans', pos: 'PF', ovr: 72, age: 33 },
];
